import { choiceQ, dots, numberQ, pick, ri, shuffle, type GradeTable, j, ye } from './grade-helpers';

const TIME_VIS = (a: number, b: number) => ({ kind: 'length-time' as const, measure: 'time' as const, values: [a, b], unit: '분' as const, clock: true });
const hm = (h: number, m: number) => (m === 0 ? `${h}시` : `${h}시 ${m}분`);
const TIME_SUM = (h: number, m: number) => ({ kind: 'length-time' as const, measure: 'time' as const, values: [h, m], unit: '분' as const, labels: [`${h}시간`, `${m}분`] });
const LEN_VIS = (values: number[], unit: 'cm' | 'm', labels?: string[]) => ({ kind: 'length-time' as const, measure: 'length' as const, values, unit, labels });
const WEEK = ['월', '화', '수', '목', '금', '토', '일'] as const;
const MONTH_DAYS = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31] as const;
const FRUITS = ['사과', '배', '귤', '포도'] as const;

export const GRADE2: GradeTable = {
  plane: [
    (r) => { const h = ri(1, 9, r), answer = h * 100; return numberQ('plane', '백 알아보기', `100이 ${h}개이면 얼마일까요?`, answer, dots('💯', [{ label: '백', icons: h }]), `100이 ${h}개이면 ${answer}${ye(answer)}.`, { hints: ['100이 몇 개인지 세어요.', `100을 ${h}번 더해요.`, `${answer}${ye(answer)}.`] }); },
    (r) => { const h = ri(1, 9, r), t = ri(0, 9, r), o = ri(0, 9, r), n = h * 100 + t * 10 + o; return choiceQ('plane', '세 자리 수', `백 모형 ${h}개, 십 모형 ${t}개, 일 모형 ${o}개를 수로 나타내면 무엇일까요?`, String(n), [String(h * 100 + o * 10 + t), String(t * 100 + h * 10 + o), String(n + 100)], dots('🟦', [{ label: '백', icons: h }, { label: '십', icons: t }, { label: '일', icons: o }]), `${h}백 ${t}십 ${o}일이므로 ${n}${ye(n)}.`, r); },
    (r) => { const k = ri(1, 9, r); return numberQ('plane', '천 알아보기', `천 모형 ${k}개는 모두 얼마일까요?`, k * 1000, dots('🟧', [{ label: '천', icons: k }]), `1000이 ${k}개이면 ${k * 1000}${ye(k * 1000)}.`); },
    (r) => { const th = ri(1, 9, r), h = ri(0, 9, r), t = ri(0, 9, r), o = ri(0, 9, r), n = th * 1000 + h * 100 + t * 10 + o, digit = pick(['천', '백', '십', '일'] as const, r); const value = digit === '천' ? th : digit === '백' ? h : digit === '십' ? t : o; return numberQ('plane', '네 자리 수', `${n}에서 ${digit}의 자리 숫자는 무엇일까요?`, value, dots('●', [{ label: String(n), icons: 4 }]), `${n}의 ${digit}의 자리 숫자는 ${value}${ye(value)}.`); },
    (r, hard) => { const a = ri(hard ? 1000 : 100, hard ? 9999 : 999, r); let b = a + (r() < .5 ? ri(1, 90, r) : -ri(1, 90, r)); if (b < (hard ? 1000 : 100)) b = a + 10; const big = r() < .5, answer = big ? Math.max(a, b) : Math.min(a, b); return choiceQ('plane', '수 비교', `${j(a, '와과')} ${b} 중 더 ${big ? '큰' : '작은'} 수는 무엇일까요?`, String(answer), [String(a === answer ? b : a)], dots('●', [{ label: '높은 자리부터', icons: 3 }]), `높은 자리부터 비교하면 ${j(answer, '이가')} 더 ${big ? '커요' : '작아요'}.`, r); },
  ],
  lengthTime: [
    (r) => { const h = ri(1, 11, r), m = pick([5, 10, 15, 20, 25, 35, 40, 45, 50, 55], r); return choiceQ('lengthTime', '몇 시 몇 분', '시계가 나타내는 시각은 몇 시 몇 분일까요?', `${h}시 ${m}분`, [`${h}시 ${m / 5}분`, `${h + 1}시 ${m}분`, `${h}시 ${(m + 10) % 60 || 30}분`], TIME_VIS(h, m), `긴바늘이 ${m / 5}이면 ${m}분이에요.`, r, { hints: ['긴바늘이 가리키는 숫자에 5를 곱하면 분이에요.', `${m / 5} × 5 = ${m}분이에요.`, `짧은바늘은 ${j(h, '을를')} 지났으므로 ${h}시 ${m}분이에요.`] }); },
    (r) => { const h = ri(1, 3, r), m = pick([10, 20, 30, 40, 50], r), answer = h * 60 + m; return numberQ('lengthTime', '시간의 합', `${h}시간 ${m}분은 모두 몇 분일까요?`, answer, TIME_SUM(h, m), `1시간은 60분이므로 ${h * 60} + ${m} = ${answer}분이에요.`, { hints: ['1시간은 60분이에요.', `${h}시간은 ${h * 60}분이에요.`, `${h * 60} + ${m} = ${answer}분이에요.`] }); },
    (r) => { const sh = ri(1, 8, r), sm = pick([0, 10, 20, 30, 40], r), dur = pick([20, 30, 40, 50], r), total = sh * 60 + sm + dur, eh = Math.floor(total / 60), em = total % 60, answer = hm(eh, em), wrongs = [hm(eh, (em + 10) % 60), hm(eh + 1, em), hm(sh, dur)].filter((w, i, all) => w !== answer && all.indexOf(w) === i); return choiceQ('lengthTime', '시각 구하기', `${hm(sh, sm)}부터 ${dur}분이 지나면 몇 시 몇 분일까요?`, answer, wrongs, TIME_VIS(sh, sm), sm === 0 ? `${sh}시에서 ${dur}분이 지나면 ${answer}${em === 0 ? '예요' : '이에요'}.` : `${sm}분에 ${dur}분을 더하면 ${sm + dur}분이에요. 60분은 1시간이므로 ${answer}${em === 0 ? '예요' : '이에요'}.`, r); },
    (r) => { const kind = ri(0, 2, r); if (kind === 0) { const d = ri(2, 4, r); return numberQ('lengthTime', '하루와 일주일', `${d}일은 몇 시간일까요? (하루는 24시간이에요)`, d * 24, { kind: 'length-time', measure: 'time', values: [d], unit: '시간', labels: [`${d}일`] }, `24 × ${d} = ${d * 24}시간이에요.`); } if (kind === 1) { const w = ri(2, 4, r); return numberQ('lengthTime', '하루와 일주일', `${w}주일은 며칠일까요? (일주일은 7일이에요)`, w * 7, { kind: 'length-time', measure: 'time', values: [w], unit: '시간', labels: [`${w}주일`] }, `7 × ${w} = ${w * 7}일이에요.`); } const m = ri(2, 5, r); return numberQ('lengthTime', '하루와 일주일', `${m}년은 몇 개월일까요? (1년은 12개월이에요)`, m * 12, { kind: 'length-time', measure: 'time', values: [m], unit: '시간', labels: [`${m}년`] }, `12 × ${m} = ${m * 12}개월이에요.`); },
    (r) => { const month = ri(0, 11, r), startDay = ri(0, 6, r), q = ri(0, 1, r); if (q === 0) { const answer = MONTH_DAYS[month]; return numberQ('lengthTime', '달력', `${month + 1}월은 며칠까지 있을까요?${month === 1 ? ' (2월은 28일로 해요)' : ''}`, answer, { kind: 'length-time', measure: 'time', values: [month + 1], unit: '시간', labels: [`${month + 1}월`] }, `${month + 1}월은 ${answer}일까지 있어요.`); } const day = WEEK[startDay], after = ri(1, 3, r) * 7, answer = day; return choiceQ('lengthTime', '달력', `오늘이 ${day}요일이에요. ${after}일 뒤는 무슨 요일일까요?`, `${answer}요일`, WEEK.filter(x => x !== answer).slice(0, 3).map(x => `${x}요일`), { kind: 'length-time', measure: 'time', values: [after], unit: '시간', labels: [`${after}일 뒤`] }, `일주일은 7일이므로 ${after}일 뒤는 같은 ${answer}요일이에요.`, r); },
  ],
  fractionDecimal: [
    (r) => { const a = ri(3, 18, r); return numberQ('fractionDecimal', 'cm로 재기', '연필의 한쪽 끝을 자의 0에 맞추어 재었어요. 연필의 길이는 몇 cm일까요?', a, { kind: 'ruler' as const, end: a }, `0에서 ${a}까지이므로 ${a} cm예요.`, { hints: ['연필의 한쪽 끝이 자의 0에 닿아 있어요.', '연필의 다른 쪽 끝이 닿은 눈금의 숫자를 읽어요.', `끝이 ${a}에 닿아 있으므로 ${a} cm예요.`] }); },
    (r) => { const k = ri(2, 6, r); return numberQ('fractionDecimal', '1 m', `1 m는 100 cm예요. ${k} m는 몇 cm일까요?`, k * 100, LEN_VIS([k], 'm'), `100 × ${k} = ${k * 100} cm예요.`); },
    (r) => { const m = ri(1, 5, r), cm = ri(1, 9, r) * 10, answer = m * 100 + cm; if (r() < .5) return numberQ('fractionDecimal', 'cm와 m', `${m} m ${cm} cm는 모두 몇 cm일까요?`, answer, LEN_VIS([m, cm], 'cm', [`${m} m`, `${cm} cm`]), `${m} m = ${m * 100} cm이므로 ${m * 100} + ${cm} = ${answer} cm예요.`); return choiceQ('fractionDecimal', 'cm와 m', `${answer} cm를 m와 cm로 나타내면 무엇일까요?`, `${m} m ${cm} cm`, [`${m} m ${cm / 10} cm`, `${cm / 10} m ${m} cm`, `${m + 1} m ${cm} cm`], LEN_VIS([answer], 'cm'), `100 cm가 ${m}번이고 ${cm} cm가 남아요.`, r); },
    (r) => { const a = ri(12, 45, r), b = ri(5, 40, r); return numberQ('fractionDecimal', '길이의 합', `${a} cm 리본과 ${b} cm 리본을 이어 붙이면 모두 몇 cm일까요?`, a + b, LEN_VIS([a, b], 'cm'), `${a} + ${b} = ${a + b} cm예요.`); },
    (r) => { const a = ri(30, 90, r), b = ri(5, a - 10, r); return numberQ('fractionDecimal', '길이의 차', `${a} cm 끈에서 ${b} cm를 잘라 냈어요. 남은 끈은 몇 cm일까요?`, a - b, LEN_VIS([a, b], 'cm'), `${a} − ${b} = ${a - b} cm예요.`); },
  ],
  circle: [
    (r) => { const answer = '곧은 선이 3개, 꼭짓점이 3개'; return choiceQ('circle', '삼각형', '삼각형의 특징은 무엇일까요?', answer, ['곧은 선이 4개, 꼭짓점이 4개', '곧은 선이 없고 둥글어요', '곧은 선이 2개, 꼭짓점이 2개'], { kind: 'geometry', shape: 'right-triangle', label: '삼각형' }, '삼각형은 변 3개와 꼭짓점 3개가 있어요.', r); },
    (r) => { const q = ri(0, 1, r); return q === 0 ? choiceQ('circle', '사각형', '사각형의 특징은 무엇일까요?', '곧은 선이 4개, 꼭짓점이 4개', ['곧은 선이 3개, 꼭짓점이 3개', '곧은 선이 없고 둥글어요', '곧은 선이 5개, 꼭짓점이 5개'], { kind: 'geometry', shape: 'rectangle', label: '사각형' }, '사각형은 변 4개와 꼭짓점 4개가 있어요.', r) : numberQ('circle', '사각형', '사각형의 꼭짓점은 모두 몇 개일까요?', 4, { kind: 'geometry', shape: 'square', label: '사각형' }, '사각형의 꼭짓점은 4개예요.'); },
    (r) => choiceQ('circle', '원', pick(['뾰족한 부분이 없고 어디에서 보아도 둥근 도형은 무엇일까요?', '곧은 선이 없고 꼭짓점도 없는 도형은 무엇일까요?'], r), '원', ['삼각형', '사각형'], { kind: 'geometry', shape: 'angle', label: '둥근 도형' }, '원은 뾰족한 부분이 없고 둥글어요.', r),
    (r) => { const tri = ri(1, 4, r), sq = ri(1, 4, r), circ = ri(1, 4, r), ask = pick(['삼각형', '사각형', '원'] as const, r), answer = ask === '삼각형' ? tri : ask === '사각형' ? sq : circ; return numberQ('circle', '도형 분류', `삼각형 ${tri}개, 사각형 ${sq}개, 원 ${circ}개를 모양에 따라 나누었어요. ${j(ask, '은는')} 모두 몇 개일까요?`, answer, dots('🔷', [{ label: '삼각형', icons: tri }, { label: '사각형', icons: sq }, { label: '원', icons: circ }]), `${ask} 모둠에는 ${answer}개가 있어요.`); },
    (r) => { const rows = ri(2, 3, r), cols = ri(2, 4, r), answer = rows * cols; return numberQ('circle', '쌓기 모양', `쌓기나무를 한 층에 ${cols}개씩 ${rows}층으로 똑같이 쌓았어요. 쌓기나무는 모두 몇 개일까요?`, answer, { kind: 'array', rows, columns: cols }, `${cols} × ${rows} = ${answer}개예요.`); },
  ],
  fraction: [
    (r) => { const s = ri(1, 6, r), step = ri(2, 5, r), seq = [s, s + step, s + step * 2, s + step * 3], answer = s + step * 4; return numberQ('fraction', '수 규칙', `${seq.join(', ')}, □ 에서 □에 알맞은 수는 무엇일까요?`, answer, dots('●', [{ label: `${step}씩`, icons: step }]), `${step}씩 커지는 규칙이므로 ${answer}${ye(answer)}.`); },
    (r) => { const set = pick([['🔴', '🔵', '🟡'], ['🍎', '🍌', '🍇'], ['⭐', '🌙', '☀️']] as const, r), seq = [set[0], set[1], set[2], set[0], set[1], set[2], set[0], set[1]]; return choiceQ('fraction', '무늬 규칙', `${seq.join(' ')} □ 에서 □에 들어갈 무늬는 무엇일까요?`, set[2], [set[0], set[1]], dots(set[0], [{ label: '규칙', icons: 3 }]), `${j(set.join(' '), '이가')} 되풀이되므로 다음은 ${set[2]}${ye(set[2])}.`, r); },
    (r) => { const n = ri(1, 4, r), add = ri(2, 3, r), seq = [n * 1, n + add, n + add * 2, n + add * 3], answer = n + add * 4; return numberQ('fraction', '늘어나는 규칙', `쌓기나무를 ${seq.join('개, ')}개로 늘려 가며 쌓았어요. 다음에 쌓을 개수는 몇 개일까요?`, answer, dots('🧱', [{ label: '1단계', icons: seq[0] }, { label: '2단계', icons: seq[1] }, { label: '3단계', icons: seq[2] }]), `${add}개씩 늘어나는 규칙이므로 ${seq[3]} + ${add} = ${answer}개예요.`); },
    (r) => { const step = ri(2, 5, r), start = step * 5 + ri(0, 4, r), seq = [start, start - step, start - step * 2, start - step * 3], answer = start - step * 4; return numberQ('fraction', '줄어드는 규칙', `수가 점점 줄어들어요: ${seq.join(', ')}, □. □에 알맞은 수는 무엇일까요?`, answer, dots('●', [{ label: `−${step}`, icons: step }]), `${step}씩 작아지는 규칙이므로 ${seq[3]} − ${step} = ${answer}${ye(answer)}.`); },
    (r) => { const step = ri(2, 5, r), start = ri(1, 5, r), seq = [start, start + step, start + step * 2], answer = `${step}씩 커져요`; return choiceQ('fraction', '규칙 설명', `${seq.join(', ')}, ${seq[2] + step}…에서 찾은 규칙으로 알맞은 것은 무엇일까요?`, answer, [`${step + 1}씩 커져요`, `${step}씩 작아져요`, `${step}배씩 커져요`], dots('●', [{ label: '규칙', icons: step }]), `수가 ${step}씩 커지고 있어요.`, r); },
  ],
  measurement: [
    (r) => { const q = ri(0, 2, r), answer = ['모양', '색깔', '크기'][q], set = ['구슬 모양이 둥근 것과 네모난 것으로', '단추가 빨강, 파랑으로', '공이 큰 것과 작은 것으로'][q]; return choiceQ('measurement', '기준 정하기', `${set} 나누려고 해요. 분류 기준은 무엇일까요?`, answer, ['모양', '색깔', '크기'].filter(x => x !== answer).concat('가격'), dots('🔘', [{ label: '분류', icons: 4 }]), `${set} 나누었으므로 기준은 ${answer}${ye(answer)}.`, r); },
    (r) => { const red = ri(2, 6, r), blue = ri(2, 6, r), ask = r() < .5 ? '빨간' : '파란'; return numberQ('measurement', '한 기준 분류', `색깔로 분류했더니 빨간 단추 ${red}개, 파란 단추 ${blue}개예요. ${ask} 단추는 몇 개일까요?`, ask === '빨간' ? red : blue, dots('🔘', [{ label: '빨강', icons: red }, { label: '파랑', icons: blue }]), `${ask} 단추 모둠은 ${ask === '빨간' ? red : blue}개예요.`); },
    (r) => { const a = ri(1, 4, r), b = ri(1, 4, r), c = ri(1, 4, r), d = ri(1, 4, r); return numberQ('measurement', '두 기준 분류', `블록을 모양과 색깔로 나누었어요. 빨간 네모 ${a}개, 파란 네모 ${b}개, 빨간 동그라미 ${c}개, 파란 동그라미 ${d}개일 때 네모는 모두 몇 개일까요?`, a + b, dots('🧱', [{ label: '빨간 네모', icons: a }, { label: '파란 네모', icons: b }, { label: '빨간 동그라미', icons: c }, { label: '파란 동그라미', icons: d }]), `네모는 ${a} + ${b} = ${a + b}개예요.`); },
    (r) => { const x = ri(2, 6, r), y = ri(2, 6, r), z = ri(2, 6, r); return numberQ('measurement', '개수 세기', `분류한 결과 사과 ${x}개, 배 ${y}개, 귤 ${z}개예요. 과일은 모두 몇 개일까요?`, x + y + z, dots('🍎', [{ label: '사과', icons: x }, { label: '배', icons: y }, { label: '귤', icons: z }]), `${x} + ${y} + ${z} = ${x + y + z}개예요.`); },
    (r) => { const counts = shuffle([ri(2, 4, r), ri(5, 7, r), ri(8, 10, r)], r), names = ['사과', '배', '귤'], most = counts.indexOf(Math.max(...counts)); return choiceQ('measurement', '분류 설명', `종류별로 세었더니 사과 ${counts[0]}개, 배 ${counts[1]}개, 귤 ${counts[2]}개예요. 가장 많은 과일은 무엇일까요?`, names[most], names.filter((_, i) => i !== most), dots('🍎', [{ label: '사과', icons: counts[0] }, { label: '배', icons: counts[1] }, { label: '귤', icons: counts[2] }]), `${counts[most]}개로 ${j(names[most], '이가')} 가장 많아요.`, r); },
  ],
  pictograph: [
    (r) => { const counts = FRUITS.map(() => ri(2, 8, r)), i = ri(0, 3, r); return numberQ('pictograph', '표 읽기', `좋아하는 과일 표예요. ${FRUITS.map((f, j) => `${f} ${counts[j]}명`).join(', ')}. ${j(FRUITS[i], '을를')} 좋아하는 친구는 몇 명일까요?`, counts[i], dots('🙂', FRUITS.map((f, j) => ({ label: f, icons: counts[j] }))), `표에서 ${j(FRUITS[i], '은는')} ${counts[i]}명이에요.`); },
    (r) => { const counts = FRUITS.map(() => ri(1, 8, r)), i = ri(0, 3, r); return numberQ('pictograph', '그래프 읽기', `○ 하나가 1명을 나타내는 그래프예요. ${FRUITS[i]} 줄에 ○가 몇 개 있을까요? (${FRUITS.map((f, j) => `${f} ${counts[j]}개`).join(', ')})`, counts[i], dots('○', FRUITS.map((f, j) => ({ label: f, icons: counts[j] }))), `${FRUITS[i]} 줄의 ○를 세면 ${counts[i]}개예요.`); },
    (r) => { const set = shuffle([ri(2, 4, r), ri(5, 6, r), ri(7, 9, r), ri(10, 12, r)], r), most = set.indexOf(Math.max(...set)); return choiceQ('pictograph', '가장 많은 것', `그래프를 보니 ${FRUITS.map((f, j) => `${f} ${set[j]}명`).join(', ')}${ye(FRUITS.map((f, j) => `${f} ${set[j]}명`).join(', '))}. 가장 많은 친구가 좋아하는 과일은 무엇일까요?`, FRUITS[most], FRUITS.filter((_, i) => i !== most), dots('○', FRUITS.map((f, j) => ({ label: f, icons: set[j] }))), `${set[most]}명으로 ${j(FRUITS[most], '이가')} 가장 많아요.`, r); },
    (r) => { const a = ri(6, 12, r), b = ri(2, a - 1, r); return numberQ('pictograph', '차이 구하기', `${j(FRUITS[0], '을를')} 좋아하는 친구는 ${a}명, ${j(FRUITS[1], '을를')} 좋아하는 친구는 ${b}명이에요. 몇 명 차이가 날까요?`, a - b, dots('○', [{ label: FRUITS[0], icons: a }, { label: FRUITS[1], icons: b }]), `${a} − ${b} = ${a - b}명 차이예요.`); },
    (r) => { const counts = FRUITS.map(() => ri(2, 7, r)), total = counts.reduce((x, y) => x + y, 0); return numberQ('pictograph', '자료 이야기', `우리 반 친구 수를 과일별로 센 표예요. ${FRUITS.map((f, j) => `${f} ${counts[j]}명`).join(', ')}. 조사한 친구는 모두 몇 명일까요?`, total, dots('🙂', FRUITS.map((f, j) => ({ label: f, icons: counts[j] }))), `${counts.join(' + ')} = ${total}명이에요.`); },
  ],
};

