import { choiceQ, dots, fmt, j, numberQ, pick, ri, shuffle, type GradeTable, ye } from './grade-helpers';

const geo = (shape: 'rectangle' | 'square' | 'right-triangle' | 'angle' | 'segment', label: string) => ({ kind: 'geometry' as const, shape, label });
const dec = (n: number) => String(parseFloat(n.toFixed(3)));
const lenVis = (label: string) => ({ kind: 'length-time' as const, measure: 'length' as const, values: [1], unit: 'cm' as const, labels: [label] });

/** 1학년: 2수01-05, 07 덧셈과 뺄셈의 의미·관계 */
export const GRADE1_EXTRA: Partial<GradeTable> = {
  fractionDecimal: [
    (r) => { const add = r() < .5, a = ri(5, 9, r), b = ri(1, a - 2, r), [name, lost] = pick([['구슬', '잃어버렸어요'], ['사탕', '먹었어요'], ['귤', '먹었어요'], ['풍선', '터뜨렸어요']] as const, r), answer = add ? `${a} + ${b} = ${a + b}` : `${a} − ${b} = ${a - b}`; return choiceQ('fractionDecimal', '이야기에 맞는 식', add ? `${j(name, '이가')} ${a}개 있었는데 ${b}개를 더 받았어요. 이야기에 맞는 식은 무엇일까요?` : `${j(name, '이가')} ${a}개 있었는데 ${b}개를 ${lost}. 이야기에 맞는 식은 무엇일까요?`, answer, add ? [`${a} − ${b} = ${a - b}`, `${a} + ${b} = ${a + b + 1}`] : [`${a} + ${b} = ${a + b}`, `${a} − ${b} = ${a - b + 1}`], dots('🔵', [{ label: name, icons: Math.min(a, 12) }]), add ? '더 받았으므로 더하기를 써요.' : '줄어들었으므로 빼기를 써요.', r); },
    (r) => { const a = ri(2, 9, r), b = ri(2, 9, r), c = a + b, kind = ri(0, 1, r); return kind === 0 ? numberQ('fractionDecimal', '덧셈과 뺄셈의 관계', `${a} + ${b} = ${c}이면 ${c} − ${b} = □에서 □는 얼마일까요?`, a, dots('●', [{ label: `${a} + ${b}`, icons: Math.min(c, 14) }]), `${a} + ${b} = ${c}이므로 ${c}에서 ${j(b, '을를')} 빼면 ${a}${ye(a)}.`) : numberQ('fractionDecimal', '덧셈과 뺄셈의 관계', `${c} − ${a} = ${b}이면 ${a} + ${b} = □에서 □는 얼마일까요?`, c, dots('●', [{ label: `${c} − ${a}`, icons: Math.min(c, 14) }]), `${c} − ${a} = ${b}이므로 ${j(a, '와과')} ${j(b, '을를')} 더하면 ${c}${ye(c)}.`); },
  ],
};

/** 2학년: 2수01-07~09 덧셈과 뺄셈 식, 2수03-01~02 입체도형·쌓기나무, 2수03-12 길이 어림 */
export const GRADE2_EXTRA: Partial<GradeTable> = {
  plane: [
    (r) => { const a = ri(20, 60, r), b = ri(10, 30, r), c = ri(5, 25, r), add = r() < .5; return numberQ('plane', '세 수의 덧셈·뺄셈', add ? `${a} + ${b} − ${j(c, '은는')} 얼마일까요?` : `${a} − ${Math.min(c, a - 5)} + ${j(b, '은는')} 얼마일까요?`, add ? a + b - c : a - Math.min(c, a - 5) + b, dots('●', [{ label: '앞에서부터', icons: 3 }]), add ? `앞에서부터 차례로 계산해요. ${a} + ${b} = ${a + b}, ${a + b} − ${c} = ${a + b - c}${ye(a + b - c)}.` : `앞에서부터 차례로 계산해요. ${a} − ${Math.min(c, a - 5)} = ${a - Math.min(c, a - 5)}, 거기에 ${j(b, '을를')} 더하면 ${a - Math.min(c, a - 5) + b}${ye(a - Math.min(c, a - 5) + b)}.`); },
    (r) => { const a = ri(11, 49, r), b = ri(11, 49, r), kind = ri(0, 1, r); return kind === 0 ? numberQ('plane', '□가 있는 식', `${a} + □ = ${a + b}에서 □에 알맞은 수는 무엇일까요?`, b, dots('□', [{ label: '모르는 수', icons: 1 }]), `${a + b} − ${a} = ${b}이므로 □는 ${b}${ye(b)}.`) : numberQ('plane', '□가 있는 식', `□ − ${a} = ${b}에서 □에 알맞은 수는 무엇일까요?`, a + b, dots('□', [{ label: '모르는 수', icons: 1 }]), `${b} + ${a} = ${a + b}이므로 □는 ${a + b}${ye(a + b)}.`); },
    (r) => { const a = ri(12, 48, r), b = ri(12, 48, r), c = a + b; return numberQ('plane', '덧셈과 뺄셈의 관계', `${a} + ${b} = ${c}이면 ${c} − ${a} = □에서 □는 얼마일까요?`, b, dots('●', [{ label: `${a} + ${b}`, icons: 3 }]), `${a} + ${b} = ${c}이므로 ${c}에서 ${j(a, '을를')} 빼면 ${b}${ye(b)}.`); },
  ],
  fractionDecimal: [
    (r) => { const items = [['연필 한 자루의 길이', '약 15 cm', ['약 15 m', '약 150 cm', '약 1 cm']], ['교실 문의 높이', '약 2 m', ['약 2 cm', '약 20 m', '약 200 m']], ['손가락 한 마디의 길이', '약 2 cm', ['약 2 m', '약 20 cm', '약 20 m']], ['교실 긴 쪽의 길이', '약 10 m', ['약 10 cm', '약 100 m', '약 1 cm']], ['지우개의 긴 쪽 길이', '약 5 cm', ['약 5 m', '약 50 cm', '약 50 m']]] as const, [what, answer, wrongs] = pick(items, r); return choiceQ('fractionDecimal', '길이 어림', `${j(what, '을를')} 어림하면 얼마쯤일까요?`, answer, [...wrongs], lenVis(what), `${j(what, '은는')} ${j(answer, '이가')} 알맞아요. 1 m는 100 cm예요.`, r); },
  ],
  circle: [
    (r) => { const items = [['축구공', '구'], ['구슬', '구'], ['통조림 캔', '원기둥'], ['두루마리 휴지', '원기둥'], ['과자 상자', '직육면체'], ['주사위', '직육면체']] as const, [what, answer] = pick(items, r); return choiceQ('circle', '입체도형 모양', `${j(what, '은는')} 직육면체, 원기둥, 구 중 어떤 모양에 가까울까요?`, answer, ['직육면체', '원기둥', '구'], geo('rectangle', what), `${j(what, '은는')} ${answer} 모양에 가까워요.`, r); },
    (r) => { const colors = shuffle(['빨간색', '파란색', '노란색', '초록색'], r), i = ri(0, 2, r), right = r() < .5, asked = right ? colors[i] : colors[i + 1], answer = right ? colors[i + 1] : colors[i]; return choiceQ('circle', '쌓기나무 위치와 방향', `왼쪽에서 오른쪽으로 ${colors.join(', ')} 쌓기나무가 한 줄로 놓여 있어요. ${asked} 쌓기나무의 바로 ${right ? '오른쪽' : '왼쪽'}에는 무슨 색이 있을까요?`, answer, colors.filter(c => c !== answer), { kind: 'array', rows: 1, columns: 4 }, `${asked} 쌓기나무의 바로 ${right ? '오른쪽' : '왼쪽'} 옆 자리에는 ${answer} 쌓기나무가 있어요.`, r); },
  ],
};

/** 4학년: 4수01-08 어림셈, 4수01-13 소수 세 자리, 4수02-02 계산식 배열, 4수03-05 점의 이동, 4수03-08 이등변·정삼각형, 4수03-11~12 정다각형·모양 만들기 */
export const GRADE4_EXTRA: Partial<GradeTable> = {
  plane: [
    (r) => { const a = ri(120, 899, r), b = ri(120, 899, r), place = 100, ra = Math.round(a / place) * place, rb = Math.round(b / place) * place, add = r() < .5; if (add) return numberQ('plane', '어림셈', `${a} + ${j(b, '을를')} 각각 백의 자리까지 반올림하여 어림하면 약 얼마일까요?`, ra + rb, dots('●', [{ label: '어림', icons: 3 }]), `${j(a, '은는')} 약 ${ra}, ${j(b, '은는')} 약 ${rb}이므로 ${ra} + ${rb} = ${ra + rb}쯤이에요.`); const lo = ri(120, 520, r), hi = lo + ri(250, 380, r); return numberQ('plane', '어림셈', `${hi} − ${j(lo, '을를')} 각각 백의 자리까지 반올림하여 어림하면 약 얼마일까요?`, Math.round(hi / place) * place - Math.round(lo / place) * place, dots('●', [{ label: '어림', icons: 3 }]), `${j(hi, '은는')} 약 ${Math.round(hi / place) * place}, ${j(lo, '은는')} 약 ${Math.round(lo / place) * place}이므로 차는 약 ${Math.round(hi / place) * place - Math.round(lo / place) * place}${ye(Math.round(hi / place) * place - Math.round(lo / place) * place)}.`); },
  ],
  lengthTime: [
    (r) => { const q = ri(0, 2, r); if (q === 0) return r() < .5 ? choiceQ('lengthTime', '이등변삼각형과 정삼각형', '두 변의 길이가 같은 삼각형은 무엇일까요?', '이등변삼각형', ['정삼각형', '직각삼각형', '둔각삼각형'], geo('right-triangle', '두 변이 같아요'), '두 변의 길이가 같은 삼각형을 이등변삼각형이라고 해요.', r) : choiceQ('lengthTime', '이등변삼각형과 정삼각형', '세 변의 길이가 모두 같은 삼각형은 무엇일까요?', '정삼각형', ['이등변삼각형', '직각삼각형', '예각삼각형'], geo('right-triangle', '세 변이 같아요'), '세 변의 길이가 모두 같은 삼각형을 정삼각형이라고 해요.', r); if (q === 1) { const top = ri(1, 8, r) * 10, base = (180 - top) / 2; return numberQ('lengthTime', '이등변삼각형과 정삼각형', `이등변삼각형에서 크기가 다른 한 각이 ${top}°예요. 나머지 두 각은 크기가 같아요. 한 각은 몇 도일까요?`, base, geo('right-triangle', `${top}°, ?, ?`), `삼각형의 세 각의 합은 180°이므로 (180 − ${top}) ÷ 2 = ${base}°예요.`); } const side = ri(2, 15, r); return numberQ('lengthTime', '이등변삼각형과 정삼각형', `정삼각형의 한 변이 ${side} cm이면 세 변의 길이의 합은 몇 cm일까요?`, side * 3, geo('right-triangle', `한 변 ${side} cm`), `세 변의 길이가 모두 같으므로 ${side} × 3 = ${side * 3} cm예요.`); },
  ],
  fractionDecimal: [
    (r) => { const x = ri(2, 6, r), y = ri(2, 5, r), dx = ri(1, 5, r), dy = ri(1, 4, r), right = r() < .5, up = r() < .5, nx = x + (right ? dx : -Math.min(dx, x - 1)), ny = y + (up ? dy : -Math.min(dy, y - 1)), answer = `(${nx}, ${ny})`, mx = right ? dx : Math.min(dx, x - 1), my = up ? dy : Math.min(dy, y - 1); return choiceQ('fractionDecimal', '점의 이동', `점이 (가로 ${x}칸, 세로 ${y}칸)에 있어요. 이 점을 ${j(right ? '오른쪽' : '왼쪽', '으로')} ${mx}칸, ${j(up ? '위쪽' : '아래쪽', '으로')} ${my}칸 옮기면 어디에 있을까요?`, answer, [`(${nx + 1}, ${ny})`, `(${nx}, ${ny + 1})`, `(${ny}, ${nx})`], { kind: 'transform', op: 'slide', label: `${right ? '오른쪽' : '왼쪽'}·${j(up ? '위쪽' : '아래쪽', '으로')} 이동` }, `가로는 ${nx}칸, 세로는 ${ny}칸이 되어 ${answer}${ye(answer)}.`, r); },
    (r) => { const q = ri(0, 1, r); if (q === 0) { const n = ri(3, 6, r), sum = n * n, line = Array.from({ length: n - 1 }, (_, k) => Array.from({ length: k + 1 }, (_, t) => 2 * t + 1).join(' + ') + ` = ${(k + 1) * (k + 1)}`).join(', '); return numberQ('fractionDecimal', '계산식 배열 규칙', `${line}처럼 홀수를 1부터 차례로 더해요. 1부터 ${2 * n - 1}까지 홀수를 모두 더하면 얼마일까요?`, sum, dots('●', [{ label: '홀수 합', icons: Math.min(n, 6) }]), `홀수를 ${n}개 더하면 ${n} × ${n} = ${sum}${ye(sum)}.`); } const n = ri(3, 5, r), ones = '1'.repeat(n), seq = Array.from({ length: n }, (_, k) => k + 1), up = seq.concat(seq.slice(0, -1).reverse()).join(''), pre = Array.from({ length: n - 2 }, (_, k) => { const m = '1'.repeat(k + 2), s = Array.from({ length: k + 2 }, (_, t) => t + 1), v = s.concat(s.slice(0, -1).reverse()).join(''); return `${m} × ${m} = ${v}`; }).slice(0, 2).join(', '); return choiceQ('fractionDecimal', '계산식 배열 규칙', `${pre}처럼 계산식에 규칙이 있어요. ${ones} × ${ones}의 결과를 규칙으로 찾으면 무엇일까요?`, fmt(Number(up)), [fmt(Number(up) + 10), fmt(Number(up) - 100 > 0 ? Number(up) - 100 : Number(up) + 100), fmt(Number(up) * 10)], dots('●', [{ label: '규칙', icons: 3 }]), `${ones} × ${ones} = ${up}${ye(up)}. 1부터 ${n}까지 올라갔다가 다시 내려오는 규칙이에요.`, r); },
  ],
  circle: [
    (r) => { const q = ri(0, 2, r); if (q === 0) return choiceQ('circle', '정다각형', '변의 길이가 모두 같고 각의 크기가 모두 같은 다각형은 무엇일까요?', '정다각형', ['이등변삼각형', '사다리꼴', '평행사변형'], geo('square', '정다각형'), '변의 길이와 각의 크기가 모두 같은 다각형을 정다각형이라고 해요.', r); const names = ['', '', '', '정삼각형', '정사각형', '정오각형', '정육각형'], n = ri(3, 6, r), s = ri(2, 12, r); if (q === 1) return numberQ('circle', '정다각형', `한 변이 ${s} cm인 ${names[n]}의 모든 변의 길이의 합은 몇 cm일까요?`, n * s, geo('square', names[n]), `${j(names[n], '은는')} 변이 ${n}개이고 길이가 모두 같으므로 ${s} × ${n} = ${n * s} cm예요.`); const n2 = ri(3, 4, r), sum = [0, 0, 0, 180, 360][n2]; return numberQ('circle', '정다각형', `${names[n2]}의 모든 각의 크기를 더하면 몇 도일까요?`, sum, geo('square', names[n2]), `${names[n2]}의 모든 각의 합은 ${sum}°예요.`); },
    (r) => { const items = [['정삼각형 2개를 변끼리 붙이면', '마름모', ['직사각형', '정사각형', '정육각형']], ['똑같은 직각삼각형 2개를 빗변끼리 붙이면', '직사각형', ['정육각형', '원', '오각형']], ['똑같은 정삼각형 6개를 둥글게 붙이면', '정육각형', ['정사각형', '직사각형', '마름모']], ['똑같은 정사각형 4개를 2줄 2칸으로 붙이면', '정사각형', ['정육각형', '삼각형', '원']]] as const, [what, answer, wrongs] = pick(items, r); return choiceQ('circle', '모양 만들기와 채우기', `${what} 어떤 도형이 될까요?`, answer, [...wrongs], geo('square', what), `${what} ${j(answer, '이가')} 만들어져요.`, r); },
  ],
  measurement: [
    (r) => { const q = ri(0, 2, r); if (q === 0) { const n = ri(2, 9, r), t = ri(1, 9, r), h = ri(1, 9, r); return choiceQ('measurement', '소수 세 자리 수', `0.${n}${t}${h}에서 소수 셋째 자리 숫자 ${j(h, '이가')} 나타내는 값은 얼마일까요?`, dec(h / 1000), [dec(h / 100), dec(h / 10), String(h)], { kind: 'decimal', tenths: n }, `소수 셋째 자리 숫자 ${j(h, '은는')} 0.001이 ${h}개이므로 ${j(dec(h / 1000), '을를')} 나타내요.`, r); } if (q === 1) { const n = ri(2, 99, r); return choiceQ('measurement', '소수 세 자리 수', `0.001이 ${n}개이면 얼마일까요?`, dec(n / 1000), [dec(n / 100), dec(n / 10), dec(n / 10000)], { kind: 'decimal', tenths: 1 }, `0.001이 ${n}개이면 ${dec(n / 1000)}${ye(dec(n / 1000))}.`, r); } const a = ri(101, 899, r), b = ri(101, 899, r) % 100 + 10; const x = a / 1000, y = b / 100, big = Math.max(x, y); if (Math.abs(x - y) < .0005) return choiceQ('measurement', '소수 세 자리 수', '0.123과 0.13 중 더 큰 수는 무엇일까요?', '0.13', ['0.123'], { kind: 'decimal', tenths: 1 }, '0.13 = 0.130이므로 0.130이 0.123보다 커요.', r); return choiceQ('measurement', '소수 세 자리 수', `${j(dec(x), '와과')} ${dec(y)} 중 더 큰 수는 무엇일까요?`, dec(big), [dec(Math.min(x, y))], { kind: 'decimal', tenths: Math.round(big * 10) % 10 }, '소수점 아래 자릿수를 맞추어 높은 자리부터 비교해요.', r); },
  ],
};
