import { choiceQ, dots, fracBar, fracText, gcd, lcm, numberQ, pick, ri, type GradeTable, j, ye } from './grade-helpers';

const geo = (shape: 'rectangle' | 'square' | 'right-triangle' | 'angle' | 'segment', label: string) => ({ kind: 'geometry' as const, shape, label });
const bar = (labels: string[], values: number[], unit: string, hidden: number[] = []) => ({ kind: 'bar-graph' as const, labels, values, unit, hidden });
const divisorsOf = (n: number) => Array.from({ length: n }, (_, i) => i + 1).filter(x => n % x === 0);
/** 소수점 아래 places 자리 소수를 정수값으로부터 정확히 써요. */
const fromInt = (value: number, places: number) => { const s = String(value).padStart(places + 1, '0'); const whole = s.slice(0, s.length - places), frac = s.slice(s.length - places).replace(/0+$/, ''); return frac ? `${whole}.${frac}` : whole; };
const PAIRS = [[12, 18], [8, 12], [12, 16], [18, 24], [10, 15], [16, 24], [20, 30], [9, 12], [14, 21], [15, 25]] as const;
const COIN = ['불가능하다', '~아닐 것 같다', '반반이다', '~일 것 같다', '확실하다'] as const;

export const GRADE5: GradeTable = {
  plane: [
    (r) => { const n = ri(12, 48, r), ds = divisorsOf(n), answer = pick(ds, r), wrongs = [n - 1, n + 1, n + 2, n - 2].filter(x => n % x !== 0 && x > 0); return choiceQ('plane', '약수', `${n}의 약수인 것은 어느 것일까요?`, String(answer), wrongs.map(String), dots('●', [{ label: String(n), icons: Math.min(8, ds.length) }]), `${j(n, '을를')} 나누어떨어지게 하는 수가 약수예요. ${n} ÷ ${answer} = ${n / answer}이므로 ${j(answer, '은는')} 약수예요.`, r); },
    (r) => { const k = ri(3, 9, r), m = ri(2, 9, r), answer = k * m; return choiceQ('plane', '배수', `${k}의 배수인 것은 어느 것일까요?`, String(answer), [answer + 1, answer - 1, answer + 2].map(String), dots('●', [{ label: `${k}씩`, icons: k }]), `${k} × ${m} = ${answer}이므로 ${j(answer, '은는')} ${k}의 배수예요.`, r); },
    (r) => { const [a, b] = pick(PAIRS, r), g = gcd(a, b), commons = divisorsOf(g).filter(x => x > 1), answer = pick(commons, r), wrongs = divisorsOf(a).concat(divisorsOf(b)).filter(x => g % x !== 0); return choiceQ('plane', '공약수', `${j(a, '와과')} ${b}의 공약수인 것은 어느 것일까요? (1은 제외해요)`, String(answer), [...new Set(wrongs)].slice(0, 5).map(String), dots('●', [{ label: String(a), icons: 3 }, { label: String(b), icons: 3 }]), `${j(a, '와과')} ${j(b, '을를')} 모두 나누어떨어지게 하는 수가 공약수예요.`, r); },
    (r) => { const [a, b] = pick(PAIRS, r); return numberQ('plane', '최대공약수', `${j(a, '와과')} ${b}의 최대공약수는 얼마일까요?`, gcd(a, b), dots('●', [{ label: String(a), icons: 3 }, { label: String(b), icons: 3 }]), `${a}의 약수와 ${b}의 약수 중 공통인 가장 큰 수는 ${gcd(a, b)}${ye(gcd(a, b))}.`, { hints: [`${a}의 약수를 모두 써 봐요.`, `${b}의 약수와 비교해 공통인 수를 찾아요.`, `공통인 약수 중 가장 큰 수는 ${gcd(a, b)}${ye(gcd(a, b))}.`] }); },
    (r) => { const [a, b] = pick([[4, 6], [6, 8], [3, 5], [4, 10], [6, 9], [8, 12], [5, 10], [6, 15]] as const, r); return numberQ('plane', '최소공배수', `${j(a, '와과')} ${b}의 최소공배수는 얼마일까요?`, lcm(a, b), dots('●', [{ label: String(a), icons: 3 }, { label: String(b), icons: 3 }]), `${a}의 배수와 ${b}의 배수 중 공통인 가장 작은 수는 ${lcm(a, b)}${ye(lcm(a, b))}.`, { hints: [`${a}의 배수를 차례로 써 봐요.`, `${b}의 배수 중 같은 수를 찾아요.`, `공통인 배수 중 가장 작은 수는 ${lcm(a, b)}${ye(lcm(a, b))}.`] }); },
  ],
  lengthTime: [
    (r) => { const a = ri(2, 9, r), b = ri(2, 9, r), c = ri(2, 9, r), form = ri(0, 2, r); if (form === 0) return numberQ('lengthTime', '혼합 계산', `${a} + ${b} × ${j(c, '을를')} 계산하면 얼마일까요?`, a + b * c, dots('●', [{ label: '곱셈 먼저', icons: 2 }]), `곱셈을 먼저 계산해 ${b} × ${c} = ${b * c}, 이어서 ${j(a, '을를')} 더해 ${a + b * c}${ye(a + b * c)}.`); if (form === 1) { const x = b * c + ri(1, 9, r); return numberQ('lengthTime', '혼합 계산', `${x} − ${b} × ${j(c, '을를')} 계산하면 얼마일까요?`, x - b * c, dots('●', [{ label: '곱셈 먼저', icons: 2 }]), `곱셈 ${b} × ${c} = ${j(b * c, '을를')} 먼저 계산하고 ${x}에서 빼면 ${x - b * c}${ye(x - b * c)}.`); } const q = ri(2, 9, r); return numberQ('lengthTime', '혼합 계산', `${a} + ${b * q} ÷ ${j(q, '을를')} 계산하면 얼마일까요?`, a + b, dots('●', [{ label: '나눗셈 먼저', icons: 2 }]), `나눗셈 ${b * q} ÷ ${q} = ${j(b, '을를')} 먼저 계산하고 ${j(a, '을를')} 더하면 ${a + b}${ye(a + b)}.`); },
    (r) => { const form = ri(0, 2, r); if (form === 0) { const a = ri(2, 9, r), b = ri(2, 9, r), c = ri(2, 9, r); return numberQ('lengthTime', '괄호', `(${a} + ${b}) × ${j(c, '을를')} 계산하면 얼마일까요?`, (a + b) * c, dots('●', [{ label: '괄호 먼저', icons: 2 }]), `괄호 안을 먼저 계산해 ${a + b} × ${c} = ${(a + b) * c}${ye((a + b) * c)}.`); } if (form === 1) { const b = ri(2, 6, r), c = ri(2, 9, r), a = b + ri(1, 6, r); return numberQ('lengthTime', '괄호', `${c} × (${a} − ${b})를 계산하면 얼마일까요?`, c * (a - b), dots('●', [{ label: '괄호 먼저', icons: 2 }]), `괄호 안 ${a} − ${b} = ${j(a - b, '을를')} 먼저 계산하고 ${j(c, '을를')} 곱하면 ${c * (a - b)}${ye(c * (a - b))}.`); } const d = ri(2, 6, r), x = ri(1, 5, r) * d, y = d * ri(1, 5, r); return numberQ('lengthTime', '괄호', `(${x} + ${y}) ÷ ${j(d, '을를')} 계산하면 얼마일까요?`, (x + y) / d, dots('●', [{ label: '괄호 먼저', icons: 2 }]), `괄호 안 ${x} + ${y} = ${j(x + y, '을를')} 먼저 계산하고 ${j(d, '으로')} 나누면 ${(x + y) / d}${ye((x + y) / d)}.`); },
    (r) => { const form = ri(0, 1, r), x = ri(3, 9, r); if (form === 0) { const k = ri(2, 6, r); return numberQ('lengthTime', '대응 관계', `탁자 1개에 의자가 ${k}개씩 있어요. 탁자가 ${x}개이면 의자는 모두 몇 개일까요?`, x * k, dots('🪑', [{ label: '탁자 1개', icons: k }, { label: '탁자 2개', icons: k * 2 }]), `${x} × ${k} = ${x * k}개예요.`); } const k = ri(2, 7, r); return numberQ('lengthTime', '대응 관계', `동생의 나이는 ${x}살이고 형은 동생보다 ${k}살 많아요. 형의 나이는 몇 살일까요?`, x + k, dots('🎂', [{ label: '동생', icons: Math.min(x, 9) }]), `${x} + ${k} = ${x + k}살이에요.`); },
    (r) => { const lo = ri(10, 40, r), hi = lo + ri(8, 20, r), inclusive = r() < .5, edge = r() < .5 ? lo : hi, inside = ri(lo + 1, hi - 1, r); const range = inclusive ? `${lo} 이상 ${hi} 이하` : `${lo} 초과 ${hi} 미만`; return choiceQ('lengthTime', '수의 범위', `${range}인 수에 포함되는 것은 어느 것일까요?`, String(inclusive ? edge : inside), inclusive ? (edge === lo ? [lo - 1, hi + 1, hi + 2] : [hi + 1, lo - 1, lo - 2]).map(String) : [lo, hi, hi + 1].map(String), dots('●', [{ label: '범위', icons: 3 }]), inclusive ? `${range}에는 ${j(edge, '이가')} 포함돼요. 이상과 이하는 그 수를 포함해요.` : `${lo} 초과 ${hi} 미만에는 ${j(lo, '와과')} ${j(hi, '이가')} 포함되지 않아요. ${j(inside, '이가')} 포함돼요.`, r); },
    (r) => { const place = pick([10, 100] as const, r), kind = pick(['올림', '버림', '반올림'] as const, r); let n = ri(101, 989, r); if (n % place === 0) n++; const up = Math.ceil(n / place) * place, down = Math.floor(n / place) * place, round = Math.round(n / place) * place, answer = kind === '올림' ? up : kind === '버림' ? down : round; return numberQ('lengthTime', '올림·버림·반올림', `${j(n, '을를')} ${place === 10 ? '십' : '백'}의 자리까지 나타내려고 ${kind}해요. 얼마가 될까요?`, answer, dots('●', [{ label: kind, icons: 2 }]), kind === '올림' ? `구하려는 자리 아래 수를 올려 ${answer}${ye(answer)}.` : kind === '버림' ? `구하려는 자리 아래 수를 버려 ${answer}${ye(answer)}.` : `구하려는 자리 바로 아래 숫자가 5 이상이면 올리고 4 이하이면 버려 ${answer}${ye(answer)}.`, { hints: ['구하려는 자리 아래의 숫자를 살펴봐요.', kind === '올림' ? '아래 수가 0이 아니면 윗자리를 1 올려요.' : kind === '버림' ? '아래 수를 모두 0으로 만들어요.' : '5 이상이면 올리고, 4 이하이면 버려요.', `${answer}${ye(answer)}.`] }); },
  ],
  fractionDecimal: [
    (r) => { const a = ri(2, 9, r), b = ri(2, 9, r), p = a * b; return choiceQ('fractionDecimal', '소수×자연수', `0.${a} × ${j(b, '은는')} 얼마일까요?`, fromInt(p, 1), [fromInt(p, 2), fromInt(p * 10, 1), fromInt(p + 1, 1)], { kind: 'decimal', tenths: a }, `${j(`0.${a}`, '은는')} 0.1이 ${a}개이므로 ${a} × ${b} = ${p}개, 즉 ${fromInt(p, 1)}${ye(fromInt(p, 1))}.`, r); },
    (r) => { const b = ri(2, 9, r), a = ri(2, 9, r), p = a * b; return choiceQ('fractionDecimal', '자연수×소수', `${b} × ${j(`0.${a}`, '은는')} 얼마일까요?`, fromInt(p, 1), [fromInt(p, 2), fromInt(p * 10, 1), fromInt(p - 1, 1)], { kind: 'decimal', tenths: a }, `${b} × 0.${a} = ${b} × ${a} ÷ 10 = ${fromInt(p, 1)}${ye(fromInt(p, 1))}.`, r); },
    (r) => { let a = ri(11, 49, r); if (a % 10 === 0) a++; const b = ri(2, 9, r), p = a * b; return choiceQ('fractionDecimal', '소수 한 자리 곱셈', `${fromInt(a, 1)} × ${j(`0.${b}`, '은는')} 얼마일까요?`, fromInt(p, 2), [fromInt(p, 1), fromInt(p, 3), fromInt(p * 10, 2)], { kind: 'decimal', tenths: b }, `${a} × ${b} = ${p}이고 소수점 아래 자릿수의 합이 2이므로 ${fromInt(p, 2)}${ye(fromInt(p, 2))}.`, r); },
    (r) => { let a = ri(12, 99, r); if (a % 10 === 0) a++; const b = ri(2, 9, r), p = a * b; return choiceQ('fractionDecimal', '소수 두 자리 곱셈', `${fromInt(a, 2)} × ${j(fromInt(b, 1), '은는')} 얼마일까요?`, fromInt(p, 3), [fromInt(p, 2), fromInt(p, 4), fromInt(p * 10, 3)], { kind: 'decimal', tenths: b }, `${a} × ${b} = ${p}이고 소수점 아래 자릿수의 합이 3이므로 ${fromInt(p, 3)}${ye(fromInt(p, 3))}.`, r); },
    (r) => { const n = ri(2, 9, r), small = pick([.2, .5, .8], r), big = pick([1.2, 1.5, 2.5], r), isSmall = r() < .5, factor = isSmall ? small : big; return choiceQ('fractionDecimal', '곱의 크기', `${n} × ${factor}의 계산 결과는 ${n}보다 커질까요, 작아질까요?`, isSmall ? `${n}보다 작아요` : `${n}보다 커요`, [isSmall ? `${n}보다 커요` : `${n}보다 작아요`, `${j(n, '와과')} 같아요`], { kind: 'decimal', tenths: Math.round(Math.min(.9, factor) * 10) }, isSmall ? '1보다 작은 수를 곱하면 곱이 처음 수보다 작아져요.' : '1보다 큰 수를 곱하면 곱이 처음 수보다 커져요.', r); },
  ],
  circle: [
    (r) => { const q = ri(0, 1, r); return q === 0 ? choiceQ('circle', '합동', '서로 포개었을 때 완전히 겹치는 두 도형을 무엇이라고 할까요?', '합동', ['대칭', '수직', '평행'], geo('rectangle', '완전히 겹쳐요'), '모양과 크기가 같아 완전히 겹치는 도형은 합동이에요.', r) : choiceQ('circle', '합동', '두 도형이 합동이면 넓이는 어떨까요?', '서로 같아요', ['서로 달라요', '한쪽이 더 넓어요', '알 수 없어요'], geo('rectangle', '합동인 두 도형'), '합동인 도형은 모양과 크기가 같으므로 넓이도 같아요.', r); },
    (r) => { const set = ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ'], i = ri(0, 2, r); return choiceQ('circle', '대응점', `삼각형 ${set[0]}${set[1]}${j(set[2], '와과')} 삼각형 ${set[3]}${set[4]}${j(set[5], '이가')} 합동이에요. 점 ${set[0]}, ${set[1]}, ${set[2]}의 대응점이 차례로 ${set[3]}, ${set[4]}, ${set[5]}일 때 점 ${['ㄱ', 'ㄴ', 'ㄷ'][i]}의 대응점은 어느 것일까요?`, set[3 + i], set.filter((_, k) => k !== 3 + i && k >= 3).concat(set[ri(0, 2, r)]), geo('right-triangle', '합동인 두 삼각형'), `차례로 짝을 지으면 점 ${['ㄱ', 'ㄴ', 'ㄷ'][i]}의 대응점은 점 ${set[3 + i]}${ye(set[3 + i])}.`, r); },
    (r) => { const len = ri(4, 15, r), ang = ri(3, 8, r) * 10, ask = r() < .5; return ask ? numberQ('circle', '대응변', `삼각형 ㄱㄴㄷ과 삼각형 ㄹㅁㅂ이 합동이에요. 변 ㄱㄴ의 길이가 ${len} cm이면 대응변 ㄹㅁ의 길이는 몇 cm일까요?`, len, geo('right-triangle', `변 ㄱㄴ ${len} cm`), '합동인 도형에서 대응변의 길이는 서로 같아요.') : numberQ('circle', '대응변', `삼각형 ㄱㄴㄷ과 삼각형 ㄹㅁㅂ이 합동이에요. 각 ㄱ이 ${ang}°이면 대응각 ㄹ은 몇 도일까요?`, ang, geo('angle', `각 ㄱ ${ang}°`), '합동인 도형에서 대응각의 크기는 서로 같아요.'); },
    (r) => { const d = ri(2, 12, r), q = ri(0, 1, r); return q === 0 ? numberQ('circle', '선대칭', `선대칭도형에서 대응점 ㄱ이 대칭축에서 ${d} cm 떨어져 있어요. 대응점 ㄱ'은 대칭축에서 몇 cm 떨어져 있을까요?`, d, geo('rectangle', '대칭축으로 접어요'), '대응점에서 대칭축까지의 거리는 서로 같아요.') : choiceQ('circle', '선대칭', '선대칭도형에서 대칭축은 대응점을 이은 선분과 어떻게 만날까요?', '수직으로 만나요', ['평행해요', '만나지 않아요', '비스듬히 만나요'], geo('rectangle', '대칭축'), '대칭축은 대응점을 이은 선분을 수직으로 둘로 똑같이 나눠요.', r); },
    (r) => { const d = ri(2, 12, r), q = ri(0, 1, r); return q === 0 ? numberQ('circle', '점대칭', `점대칭도형에서 대응점 ㄱ이 대칭의 중심에서 ${d} cm 떨어져 있어요. 대응점 ㄴ은 대칭의 중심에서 몇 cm 떨어져 있을까요?`, d, geo('square', '대칭의 중심'), '대응점에서 대칭의 중심까지의 거리는 서로 같아요.') : choiceQ('circle', '점대칭', '점대칭도형은 대칭의 중심을 기준으로 몇 도 돌렸을 때 처음 도형과 완전히 겹칠까요?', '180°', ['90°', '45°', '360°를 돌려야만 겹쳐요'], geo('square', '점대칭'), '점대칭도형은 180° 돌리면 처음 도형과 완전히 겹쳐요.', r); },
  ],
  fraction: [
    (r) => { const [a, b] = pick([[1, 2], [1, 3], [2, 3], [1, 4], [3, 4], [2, 5], [3, 5], [1, 5], [4, 5], [1, 6], [5, 6], [2, 7], [3, 7], [4, 7], [3, 8], [5, 8], [2, 9], [5, 9]] as const, r), g = ri(2, 5, r), n = a * g, d = b * g, answer = `${a}/${b}`; return choiceQ('fraction', '약분', `${j(`${n}/${d}`, '을를')} 약분하여 기약분수로 나타내면 무엇일까요?`, answer, [`${n}/${d}`, `${a + 1}/${b}`, `${a}/${b + 1}`], fracBar(Math.min(n, d), d), `분자와 분모를 최대공약수 ${j(g, '으로')} 나누면 ${answer}${ye(answer)}.`, r); },
    (r) => { const [d1, d2] = pick([[2, 3], [2, 5], [3, 4], [4, 6], [3, 6], [4, 10], [6, 9]] as const, r); return numberQ('fraction', '통분', `${j(`${1}/${d1}`, '와과')} ${j(`${1}/${d2}`, '을를')} 통분할 때 공통분모가 될 수 있는 가장 작은 수는 얼마일까요?`, lcm(d1, d2), fracBar(1, d1), `${j(d1, '와과')} ${d2}의 최소공배수 ${j(lcm(d1, d2), '이가')} 가장 작은 공통분모예요.`, { hints: [`${d1}의 배수와 ${d2}의 배수를 살펴봐요.`, '두 분모의 공통인 배수를 찾아요.', `가장 작은 공통인 배수는 ${lcm(d1, d2)}${ye(lcm(d1, d2))}.`] }); },
    (r) => { const [d1, d2] = pick([[2, 3], [2, 5], [3, 4], [3, 5], [4, 6], [2, 7]] as const, r), n1 = ri(1, d1 - 1, r), n2 = ri(1, d2 - 1, r), L = lcm(d1, d2), n = n1 * (L / d1) + n2 * (L / d2), answer = fracText(n, L); return choiceQ('fraction', '분수 덧셈', `${n1}/${d1} + ${j(`${n2}/${d2}`, '은는')} 얼마일까요?`, answer, [`${n1 + n2}/${d1 + d2}`, fracText(n + 1, L), fracText(n1 + n2, L)], fracBar(Math.min(n, L), L), `통분하여 분모를 ${j(L, '으로')} 같게 한 뒤 더하면 ${answer}${ye(answer)}.`, r); },
    (r) => { const [d1, d2] = pick([[2, 3], [2, 5], [3, 4], [3, 5], [4, 6], [2, 7]] as const, r), L = lcm(d1, d2); let a: { n: number; d: number } = { n: ri(1, d1 - 1, r), d: d1 }, b: { n: number; d: number } = { n: ri(1, d2 - 1, r), d: d2 }; if (a.n * b.d === b.n * a.d) { a = { n: a.d - 1, d: a.d }; b = { n: 1, d: b.d }; } else if (a.n * b.d < b.n * a.d) [a, b] = [b, a]; const top = a.n * (L / a.d) - b.n * (L / b.d), answer = fracText(top, L); return choiceQ('fraction', '분수 뺄셈', `${a.n}/${a.d} − ${j(`${b.n}/${b.d}`, '은는')} 얼마일까요?`, answer, [`${Math.max(1, a.n - b.n)}/${a.d}`, `${Math.max(1, a.n - b.n)}/${a.d + b.d}`, fracText(top + 1, L)], fracBar(Math.min(a.n * (L / a.d), L), L), `통분하여 분모를 ${j(L, '으로')} 같게 한 뒤 빼면 ${answer}${ye(answer)}.`, r); },
    (r) => { const d = ri(3, 9, r), n = ri(1, d - 1, r), m = ri(2, 6, r); if (r() < .5) { const answer = fracText(n * m, d); return choiceQ('fraction', '분수 곱셈', `${n}/${d} × ${j(m, '은는')} 얼마일까요?`, answer, [fracText(n, d * m), fracText(n * m, d * m), fracText(n + m, d)], fracBar(n, d), `분자에 ${j(m, '을를')} 곱하면 ${n * m}/${d} = ${answer}${ye(answer)}.`, r); } const n2 = ri(1, 4, r), d2 = ri(n2 + 1, 6, r), answer = fracText(n * n2, d * d2); return choiceQ('fraction', '분수 곱셈', `${n}/${d} × ${j(`${n2}/${d2}`, '은는')} 얼마일까요?`, answer, [fracText(n + n2, d + d2), fracText(n * d2, d * n2), fracText(n * n2, d + d2)], fracBar(n, d), `분자끼리, 분모끼리 곱하면 ${n * n2 + '/' + d * d2 === answer ? '' : `${n * n2}/${d * d2} = `}${answer}${ye(answer)}.`, r); },
  ],
  measurement: [
    (r) => { if (r() < .5) { const w = ri(3, 15, r), h = ri(2, 12, r); return numberQ('measurement', '다각형 둘레', `가로 ${w} cm, 세로 ${h} cm인 직사각형의 둘레는 몇 cm일까요?`, (w + h) * 2, geo('rectangle', `${w} cm × ${h} cm`), `(${w} + ${h}) × 2 = ${(w + h) * 2} cm예요.`); } const n = ri(3, 8, r), s = ri(2, 12, r), name = ['', '', '', '정삼각형', '정사각형', '정오각형', '정육각형', '정칠각형', '정팔각형'][n]; return numberQ('measurement', '다각형 둘레', `한 변이 ${s} cm인 ${name}의 둘레는 몇 cm일까요?`, n * s, geo('square', name), `${s} × ${n} = ${n * s} cm예요.`); },
    (r) => { const w = ri(3, 12, r), h = ri(2, 9, r); return numberQ('measurement', '평행사변형 넓이', `밑변 ${w} cm, 높이 ${h} cm인 평행사변형의 넓이는 몇 cm²일까요?`, w * h, geo('rectangle', `밑변 ${w} cm, 높이 ${h} cm`), `평행사변형의 넓이 = 밑변 × 높이 = ${w} × ${h} = ${w * h} cm²예요.`); },
    (r) => { const w = ri(2, 10, r) * 2, h = ri(2, 9, r); return numberQ('measurement', '삼각형 넓이', `밑변 ${w} cm, 높이 ${h} cm인 삼각형의 넓이는 몇 cm²일까요?`, w * h / 2, geo('right-triangle', `밑변 ${w} cm, 높이 ${h} cm`), `삼각형의 넓이 = 밑변 × 높이 ÷ 2 = ${w} × ${h} ÷ 2 = ${w * h / 2} cm²예요.`); },
    (r) => { const a = ri(2, 8, r), b = ri(2, 8, r) + 1, h = (a + b) % 2 === 0 ? ri(2, 9, r) : ri(1, 5, r) * 2, area = (a + b) * h / 2; return numberQ('measurement', '사다리꼴 넓이', `윗변 ${a} cm, 아랫변 ${b} cm, 높이 ${h} cm인 사다리꼴의 넓이는 몇 cm²일까요?`, area, geo('rectangle', `${a} cm, ${b} cm, 높이 ${h} cm`), `(${a} + ${b}) × ${h} ÷ 2 = ${area} cm²예요.`); },
    (r) => { const q = ri(0, 3, r), a = ri(2, 9, r); if (q === 0) return numberQ('measurement', '직육면체', '직육면체의 면은 모두 몇 개일까요?', 6, geo('rectangle', '직육면체'), '직육면체는 직사각형 모양의 면이 6개예요.'); if (q === 1) return numberQ('measurement', '직육면체', '직육면체의 모서리는 모두 몇 개일까요?', 12, geo('rectangle', '직육면체'), '직육면체의 모서리는 12개예요.'); if (q === 2) return numberQ('measurement', '직육면체', '직육면체의 꼭짓점은 모두 몇 개일까요?', 8, geo('rectangle', '직육면체'), '직육면체의 꼭짓점은 8개예요.'); return numberQ('measurement', '직육면체', `한 모서리가 ${a} cm인 정육면체의 모든 모서리의 길이의 합은 몇 cm일까요?`, 12 * a, geo('square', '정육면체'), `정육면체의 모서리 12개의 길이가 모두 같으므로 ${a} × 12 = ${12 * a} cm예요.`); },
  ],
  pictograph: [
    (r) => { const vals = [ri(1, 9, r), ri(1, 9, r), ri(1, 9, r), 0]; const sum = vals[0] + vals[1] + vals[2]; vals[3] = (4 - (sum % 4)) % 4 + 4; const avg = vals.reduce((x, y) => x + y, 0) / 4; return numberQ('pictograph', '평균', `네 날 동안 읽은 쪽수는 ${vals.join(', ')}쪽이에요. 하루 평균은 몇 쪽일까요?`, avg, bar(['1일', '2일', '3일', '4일'], vals, '쪽'), `합 ${j(vals.reduce((x, y) => x + y, 0), '을를')} 4로 나누면 평균은 ${avg}쪽이에요.`); },
    (r) => { const n = ri(3, 6, r), avg = ri(5, 20, r); return numberQ('pictograph', '평균으로 합계 구하기', `${n}회 동안 한 줄넘기 기록의 평균이 ${avg}번이에요. ${n}회의 기록을 모두 합하면 몇 번일까요?`, n * avg, dots('●', [{ label: '평균', icons: Math.min(avg, 10) }]), `평균 × 횟수 = ${avg} × ${n} = ${n * avg}번이에요.`); },
    (r) => { const red = ri(5, 9, r), blue = ri(1, 3, r); return choiceQ('pictograph', '가능성 비교', `주머니에 빨간 구슬 ${red}개와 파란 구슬 ${blue}개가 들어 있어요. 구슬 하나를 꺼낼 때 어느 색이 나올 가능성이 더 높을까요?`, '빨간 구슬', ['파란 구슬', '두 색의 가능성이 같아요'], dots('🔴', [{ label: '빨강', icons: red }, { label: '파랑', icons: blue }]), '개수가 더 많은 빨간 구슬이 나올 가능성이 더 높아요.', r); },
    (r) => { const items = [['주사위를 던질 때 7의 눈이 나올 가능성', '불가능하다'], ['동전을 던질 때 그림 면이 나올 가능성', '반반이다'], ['내일 해가 동쪽에서 뜰 가능성', '확실하다'], ['10개 중 9개가 당첨인 제비에서 당첨이 나올 가능성', '~일 것 같다'], ['10개 중 1개가 당첨인 제비에서 당첨이 나올 가능성', '~아닐 것 같다']] as const, [what, answer] = pick(items, r); return choiceQ('pictograph', '가능성 표현', `${j(what, '을를')} 말로 나타내면 알맞은 것은 무엇일까요?`, answer, COIN.filter(x => x !== answer), dots('🎲', [{ label: '가능성', icons: 3 }]), `${j(what, '은는')} “${answer}”라고 나타내요.`, r); },
    (r) => { const avgA = ri(7, 10, r), avgB = ri(4, 6, r), dev = () => { const d = [ri(-1, 1, r), ri(-1, 1, r), ri(-1, 1, r)]; return [...d, -d.reduce((x, y) => x + y, 0)]; }, a = dev().map(x => avgA + x), b = dev().map(x => avgB + x), flip = r() < .5, first = flip ? b : a, second = flip ? a : b, answer = flip ? '나 모둠' : '가 모둠'; return choiceQ('pictograph', '자료 해석', `가 모둠의 기록은 ${first.join(', ')}점, 나 모둠의 기록은 ${second.join(', ')}점이에요. 평균 점수가 더 높은 모둠은 어디일까요?`, answer, ['가 모둠', '나 모둠', '평균이 같아요'].filter(x => x !== answer), bar(['가 모둠 평균', '나 모둠 평균'], [first.reduce((x, y) => x + y, 0) / 4, second.reduce((x, y) => x + y, 0) / 4], '점'), `가 모둠 평균은 ${first.reduce((x, y) => x + y, 0) / 4}점, 나 모둠 평균은 ${second.reduce((x, y) => x + y, 0) / 4}점이에요.`, r); },
  ],
};

