import { choiceQ, dots, near, numberQ, pick, ri, shuffle, type GradeTable, j, ye } from './grade-helpers';

const ICONS = [['🍎', '사과'], ['⭐', '별'], ['🐟', '물고기'], ['🍓', '딸기'], ['🌸', '꽃']] as const;
const SHAPE_OBJECTS = {
  상자: ['선물 상자', '주사위', '과자 상자', '지우개 상자'],
  공: ['축구공', '구슬', '지구본', '야구공'],
  둥근기둥: ['통조림 캔', '두루마리 휴지', '북', '음료수 캔'],
} as const;
const SHAPE_ORDER = ['상자', '공', '둥근기둥'] as const;

const shapeQuestion = (kind: (typeof SHAPE_ORDER)[number]): GradeTable['circle'][number] => (r) => {
  const answer = pick(SHAPE_OBJECTS[kind], r);
  const wrongs = SHAPE_ORDER.filter(k => k !== kind).map(k => pick(SHAPE_OBJECTS[k], r));
  const name = kind === '상자' ? '상자 모양' : kind === '공' ? '공 모양' : '둥근기둥 모양';
  const hint: Record<string, string> = { 상자: '네모난 면이 여섯 개 있고 모서리가 뾰족해요.', 공: '어느 쪽에서 봐도 둥글고 데굴데굴 잘 굴러가요.', 둥근기둥: '위아래는 평평하고 옆은 둥글어요. 눕히면 굴러가요.' };
  return choiceQ('circle', name, `다음 중 ${name}인 것은 무엇일까요?`, answer, wrongs, dots('📦', [{ label: name, icons: 1 }]), `${j(answer, '은는')} ${name}${ye(name)}.`, r, { hints: ['물건을 손으로 만져 본다고 생각해 봐요.', hint[kind], `${j(answer, '이가')} ${name}${ye(name)}.`] });
};

export const GRADE1: GradeTable = {
  plane: [
    (r) => { const n = ri(2, 9, r), [icon, name] = pick(ICONS, r); return numberQ('plane', '9까지의 수', `${j(icon, '이가')} 모두 몇 개일까요?`, n, dots(icon, [{ label: name, icons: n }]), `${j(icon, '을를')} 하나씩 세면 모두 ${n}개예요.`); },
    (r) => { const n = ri(1, 8, r), after = r() < .5, answer = after ? n + 1 : n - 1; const m = after ? n : n + 1; return choiceQ('plane', '수의 순서', `${m}보다 ${after ? '1만큼 더 큰' : '1만큼 더 작은'} 수는 무엇일까요?`, String(after ? m + 1 : m - 1), near(after ? m + 1 : m - 1, [-1, 1, 2], 0), dots('●', [{ label: `${m}`, icons: m }]), `${m} 바로 ${after ? '다음' : '앞'}의 수는 ${after ? m + 1 : m - 1}${ye(after ? m + 1 : m - 1)}.`, r); },
    (r, hard) => { const a = ri(1, hard ? 50 : 9, r); let b = ri(1, hard ? 50 : 9, r); if (b === a) b = a === 1 ? 2 : a - 1; const big = r() < .5, answer = big ? Math.max(a, b) : Math.min(a, b); return choiceQ('plane', '수 비교', `${j(a, '와과')} ${b} 중 더 ${big ? '큰' : '작은'} 수는 무엇일까요?`, String(answer), nums2([a, b].filter(x => x !== answer)), dots('●', [{ label: String(a), icons: Math.min(a, 12) }, { label: String(b), icons: Math.min(b, 12) }]), `${j(a, '와과')} ${j(b, '을를')} 비교하면 ${j(answer, '이가')} 더 ${big ? '커요' : '작아요'}.`, r); },
    (r) => { const tens = ri(1, 4, r), ones = ri(0, 9, r), answer = tens * 10 + ones; return numberQ('plane', '몇십과 몇', `10개씩 묶음이 ${tens}개, 낱개가 ${ones}개이면 모두 몇 개일까요?`, answer, dots('🔟', [{ label: '묶음', icons: tens }, { label: '낱개', icons: ones }]), `${j(tens * 10, '와과')} ${j(ones, '을를')} 합하면 ${answer}${ye(answer)}.`, { hints: ['10개씩 묶음 한 개는 10개예요.', `묶음 ${tens}개는 ${tens * 10}개예요.`, `${j(tens * 10, '와과')} 낱개 ${j(ones, '을를')} 합해요.`] }); },
    (r) => { const n = ri(11, 50, r), tens = Math.floor(n / 10), ones = n % 10, answer = `${tens}묶음 ${ones}개`; return choiceQ('plane', '50까지의 수', `${j(n, '은는')} 10개씩 묶음 몇 개와 낱개 몇 개일까요?`, answer, [`${ones}묶음 ${tens}개`, `${Math.max(0, tens - 1)}묶음 ${ones}개`, `${tens}묶음 ${(ones + 1) % 10}개`], dots('●', [{ label: `${n}`, icons: Math.min(n, 12) }]), `${n}에서 십의 자리 ${j(tens, '은는')} 묶음, 일의 자리 ${j(ones, '은는')} 낱개예요.`, r); },
  ],
  lengthTime: [
    (r) => { const h = ri(1, 11, r); return choiceQ('lengthTime', '몇 시', '시계가 나타내는 시각은 몇 시일까요?', `${h}시`, [`${h + 1}시`, `${Math.max(1, h - 1)}시`, `${h}시 30분`], { kind: 'length-time', measure: 'time', values: [h, 0], unit: '분', clock: true }, `긴바늘이 12이면 정각이므로 ${h}시예요.`, r); },
    (r) => { const h = ri(1, 11, r); return choiceQ('lengthTime', '몇 시 30분', '시계가 나타내는 시각은 몇 시 30분일까요?', `${h}시 30분`, [`${h + 1}시 30분`, `${h}시`, `${h + 1}시`], { kind: 'length-time', measure: 'time', values: [h, 30], unit: '분', clock: true }, `긴바늘이 6이면 30분이에요. 짧은바늘이 ${j(h, '을를')} 막 지났으므로 ${h}시 30분이에요.`, r); },
    (r) => { const items = [['일어나서 세수를 해요', '아침'], ['점심을 먹어요', '낮'], ['해가 지고 하늘이 붉어져요', '저녁'], ['잠을 자요', '밤'], ['학교에 가요', '아침'], ['달이 떠요', '밤']] as const, [what, answer] = pick(items, r); return choiceQ('lengthTime', '하루의 때', `“${what}”는 하루 중 언제 일어나는 일일까요?`, answer, ['아침', '낮', '저녁', '밤'].filter(x => x !== answer), { kind: 'length-time', measure: 'time', values: [1], unit: '시간', labels: ['하루'] }, `“${what}”는 ${answer}에 일어나는 일이에요.`, r); },
    (r, hard) => { const start = ri(1, 5, r), step = hard ? ri(2, 3, r) : 2, seq = [start, start + step, start + step * 2, start + step * 3], answer = start + step * 4; return numberQ('lengthTime', '수 규칙', `${seq.join(', ')}, □ 에서 □에 알맞은 수는 무엇일까요?`, answer, dots('●', [{ label: `${step}씩`, icons: step }]), `${step}씩 커지는 규칙이므로 ${seq[3]} 다음은 ${answer}${ye(answer)}.`, { hints: ['수가 얼마씩 커지는지 살펴봐요.', `${seq[0]}에서 ${j(seq[1], '이가')} 되었으니 ${step}씩 커져요.`, `${seq[3]} + ${step} = ${answer}${ye(answer)}.`] }); },
    (r) => { const set = pick([['🔴', '🔺'], ['⭐', '🌙'], ['🍎', '🍌']] as const, r), three = r() < .5, x = set[0], y = set[1], pattern = three ? [x, y, y, x, y, y, x, y] : [x, y, x, y, x, y, x], answer = y; return choiceQ('lengthTime', '모양 규칙', `${pattern.join(' ')} □ 에서 □에 들어갈 모양은 무엇일까요?`, answer, [x], { kind: 'pictograph', icon: x, value: 1, rows: [{ label: '규칙', icons: 3 }] }, three ? `${x} ${y} ${j(y, '이가')} 되풀이되므로 다음은 ${y}예요.` : `${x} ${j(y, '이가')} 번갈아 나오므로 다음은 ${y}예요.`, r); },
  ],
  fractionDecimal: [
    (r) => { const a = ri(1, 5, r), b = ri(1, 9 - a, r); return numberQ('fractionDecimal', '수 모으기', `${j(a, '와과')} ${j(b, '을를')} 모으면 몇이 될까요?`, a + b, dots('●', [{ label: `${a}`, icons: a }, { label: `${b}`, icons: b }]), `${j(a, '와과')} ${j(b, '을를')} 모으면 ${a + b}예요.`); },
    (r) => { const total = ri(4, 9, r), left = ri(1, total - 1, r); return numberQ('fractionDecimal', '수 가르기', `${j(total, '을를')} ${j(left, '와과')} □로 가르기 했어요. □는 얼마일까요?`, total - left, dots('●', [{ label: `${left}`, icons: left }, { label: '□', icons: total - left }]), `${j(total, '은는')} ${j(left, '와과')} ${j(total - left, '으로')} 가를 수 있어요.`); },
    (r) => { const a = ri(1, 9, r); return numberQ('fractionDecimal', '10 만들기', `${j(a, '와과')} □를 모으면 10이 돼요. □는 얼마일까요?`, 10 - a, dots('●', [{ label: `${a}`, icons: a }, { label: '□', icons: 10 - a }]), `${j(a, '와과')} ${j(10 - a, '을를')} 모으면 10이에요.`); },
    (r, hard) => { const n = ri(5, hard ? 18 : 10, r), a = ri(1, n - 1, r), sub = r() < .5; return numberQ('fractionDecimal', '빈칸 수', sub ? `${n} − □ = ${a}에서 □에 알맞은 수는 무엇일까요?` : `${a} + □ = ${n}에서 □에 알맞은 수는 무엇일까요?`, sub ? n - a : n - a, dots('●', [{ label: '전체', icons: Math.min(n, 14) }]), sub ? `${n}에서 ${j(n - a, '을를')} 빼면 ${a}예요.` : `${a}에 ${j(n - a, '을를')} 더하면 ${n}${ye(n)}.`); },
    (r) => { const a = ri(2, 7, r), b = ri(1, 9 - a, r), add = r() < .5, name = pick(['사과', '풍선', '구슬', '별'], r); return numberQ('fractionDecimal', '수 이야기', add ? `${j(name, '이가')} ${a}개 있었는데 ${b}개를 더 받았어요. 모두 몇 개일까요?` : `${j(name, '이가')} ${a + b}개 있었는데 ${b}개를 친구에게 주었어요. 남은 것은 몇 개일까요?`, add ? a + b : a, dots('●', [{ label: name, icons: add ? a : a + b }]), add ? `${a} + ${b} = ${a + b}개예요.` : `${a + b} − ${b} = ${a}개예요.`); },
  ],
  circle: [shapeQuestion('상자'), shapeQuestion('공'), shapeQuestion('둥근기둥'),
    (r) => { const tri = r() < .5, answer = tri ? '세모' : '네모', cond = tri ? '꼭짓점이 3개이고 곧은 선이 3개' : '꼭짓점이 4개이고 곧은 선이 4개'; return choiceQ('circle', '세모와 네모', `${cond}인 모양은 무엇일까요?`, answer, ['세모', '네모', '동그라미'].filter(x => x !== answer), { kind: 'geometry', shape: tri ? 'right-triangle' : 'rectangle', label: answer }, `${j(answer, '은는')} ${cond}예요.`, r); },
    (r) => { const answer = '동그라미'; return choiceQ('circle', '동그라미', pick(['뾰족한 곳이 없고 둥근 모양은 무엇일까요?', '곧은 선이 하나도 없는 모양은 무엇일까요?'], r), answer, ['세모', '네모'], { kind: 'geometry', shape: 'angle', label: '둥근 모양' }, '동그라미는 뾰족한 곳도 곧은 선도 없어요.', r); },
  ],
  fraction: [
    (r) => { const a = ri(1, 4, r), b = ri(1, 4, r); return numberQ('fraction', '모양 쌓기', `상자 모양을 아래에 ${a}개, 그 위에 ${b}개 쌓았어요. 모두 몇 개일까요?`, a + b, dots('📦', [{ label: '위', icons: b }, { label: '아래', icons: a }]), `${a} + ${b} = ${a + b}개예요.`); },
    (r) => { const total = ri(4, 9, r), floor = ri(2, total - 1, r), up = r() < .5, answer = up ? floor + 1 : floor - 1; return numberQ('fraction', '위와 아래', `${total}층 건물에서 ${floor}층의 바로 ${up ? '위' : '아래'}층은 몇 층일까요?`, answer, dots('🏢', [{ label: `${total}층`, icons: total }]), `${floor}층의 바로 ${up ? '위는' : '아래는'} ${answer}층이에요.`); },
    (r) => { const front = ri(1, 3, r), back = ri(1, 3, r), name = pick(['토끼', '다람쥐', '곰'], r); return numberQ('fraction', '앞과 뒤', `${name} 앞에 ${front}명, 뒤에 ${back}명이 서 있어요. 줄에 선 친구는 ${name}까지 모두 몇 명일까요?`, front + back + 1, dots('🧒', [{ label: '앞', icons: front }, { label: name, icons: 1 }, { label: '뒤', icons: back }]), `${front} + 1 + ${back} = ${front + back + 1}명이에요.`); },
    (r) => { const row = shuffle(['별', '나무', '집', '연못', '꽃'], r), i = ri(0, 3, r), right = r() < .5; const answer = right ? row[i + 1] : row[i]; const asked = right ? row[i] : row[i + 1]; return choiceQ('fraction', '왼쪽과 오른쪽', `물건이 한 줄로 놓여 있어요: ${row.join(', ')}. ${asked}의 바로 ${right ? '오른쪽' : '왼쪽'} 옆에는 무엇이 있을까요?`, answer, row.filter(x => x !== answer), dots('●', [{ label: '왼쪽→오른쪽', icons: 5 }]), `${asked}의 ${right ? '오른쪽' : '왼쪽'}에는 ${j(answer, '이가')} 있어요.`, r); },
    (r) => { const row = shuffle(['별', '나무', '집', '연못', '꽃'], r), order = ri(2, 5, r); return choiceQ('fraction', '몇 번째', `왼쪽부터 ${j(row.join(', '), '이가')} 있어요. ${order}번째에 있는 것은 무엇일까요?`, row[order - 1], row.filter((_, i) => i !== order - 1), dots('●', [{ label: '왼쪽→오른쪽', icons: 5 }]), `왼쪽부터 차례로 세면 ${order}번째는 ${row[order - 1]}${ye(row[order - 1])}.`, r); },
  ],
  measurement: [
    (r) => { const a = ri(2, 9, r); let b = ri(2, 9, r); if (b === a) b = a === 9 ? 8 : a + 1; const long = r() < .5, answer = (a > b) === long ? 'A 연필' : 'B 연필'; return choiceQ('measurement', '길이 비교', `A 연필은 ${a}칸, B 연필은 ${b}칸이에요. 더 ${long ? '긴' : '짧은'} 연필은 무엇일까요?`, answer, [answer === 'A 연필' ? 'B 연필' : 'A 연필', '같아요'], dots('▭', [{ label: 'A', icons: a }, { label: 'B', icons: b }]), `${a}칸과 ${b}칸을 비교하면 ${j(answer, '이가')} 더 ${long ? '길어요' : '짧아요'}.`.replace(`${j(answer, '이가')}`, j(answer, '이가')), r); },
    (r) => { const down = r() < .5, answer = down ? '내려간 쪽' : '올라간 쪽', thing = pick(['수박', '사과', '책가방', '공'], r); return choiceQ('measurement', '무게 비교', `시소(저울)에서 ${thing} 쪽이 ${down ? '내려갔어요' : '올라갔어요'}. ${j(thing, '은는')} 반대쪽보다 어떨까요?`, down ? '더 무거워요' : '더 가벼워요', [down ? '더 가벼워요' : '더 무거워요', '무게가 같아요'], dots('⚖️', [{ label: thing, icons: down ? 3 : 1 }]), `${j(answer, '이가')} ${down ? '더 무거워요' : '더 가벼워요'}.`, r); },
    (r) => { const a = ri(3, 12, r); let b = ri(3, 12, r); if (a === b) b = a + 1; const answer = a > b ? '가' : '나'; return choiceQ('measurement', '넓이 비교', `같은 크기의 칸으로 넓이를 쟀더니 가는 ${a}칸, 나는 ${b}칸이에요. 더 넓은 것은 무엇일까요?`, answer, [answer === '가' ? '나' : '가', '같아요'], dots('▦', [{ label: '가', icons: a }, { label: '나', icons: b }]), `${Math.max(a, b)}칸이 더 많아 ${j(answer, '이가')} 더 넓어요.`, r); },
    (r) => { const a = ri(2, 9, r); let b = ri(2, 9, r); if (a === b) b = a === 9 ? 8 : a + 1; const answer = a > b ? 'A' : 'B'; return choiceQ('measurement', '들이 비교', `같은 컵으로 물을 담았더니 물병 A에는 ${a}컵, B에는 ${b}컵이 들어가요. 물이 더 많이 들어가는 병은 무엇일까요?`, answer, [answer === 'A' ? 'B' : 'A', '같아요'], dots('🥛', [{ label: 'A', icons: a }, { label: 'B', icons: b }]), `${Math.max(a, b)}컵이 더 많아 ${answer}에 물이 더 많이 들어가요.`, r); },
    (r) => { const names = shuffle(['토끼', '다람쥐', '곰'], r), asked = r() < .5; return choiceQ('measurement', '순서 정하기', `${j(names[0], '은는')} ${names[1]}보다 키가 크고, ${j(names[1], '은는')} ${names[2]}보다 키가 커요. 키가 ${asked ? '가장 큰' : '가장 작은'} 친구는 누구일까요?`, asked ? names[0] : names[2], names.filter(x => x !== (asked ? names[0] : names[2])), dots('🧒', [{ label: names[0], icons: 3 }, { label: names[1], icons: 2 }, { label: names[2], icons: 1 }]), `${names[0]} > ${names[1]} > ${names[2]} 순서예요.`, r); },
  ],
  pictograph: [
    (r) => { const tens = ri(5, 9, r), ones = ri(0, 9, r); return numberQ('pictograph', '100까지의 수', `10개씩 묶음이 ${tens}개, 낱개가 ${ones}개이면 모두 몇 개일까요?`, tens * 10 + ones, dots('🔟', [{ label: '묶음', icons: tens }, { label: '낱개', icons: ones }]), `${j(tens * 10, '와과')} ${j(ones, '을를')} 합하면 ${tens * 10 + ones}${ye(tens * 10 + ones)}.`); },
    (r) => { const k = ri(2, 10, r); return numberQ('pictograph', '10개씩 묶기', `${j(k * 10, '은는')} 10개씩 묶음 몇 개일까요?`, k, dots('🔟', [{ label: '묶음', icons: k }]), `10개씩 ${k}묶음이 ${k * 10}${ye(k * 10)}.`); },
    (r) => { const n = ri(52, 98, r), before = r() < .5; return choiceQ('pictograph', '수의 순서', `${n} 바로 ${before ? '앞' : '다음'}의 수는 무엇일까요?`, String(before ? n - 1 : n + 1), near(before ? n - 1 : n + 1, before ? [-1, 1, 2] : [-1, 1, -2]), dots('●', [{ label: `${n}`, icons: Math.min(10, n % 10 || 10) }]), `${n}보다 1 ${before ? '작은' : '큰'} 수는 ${before ? n - 1 : n + 1}${ye(before ? n - 1 : n + 1)}.`, r); },
    (r) => { const a = ri(30, 99, r); let b = ri(30, 99, r); if (a === b) b = a - 1; const big = r() < .5, answer = big ? Math.max(a, b) : Math.min(a, b); return choiceQ('pictograph', '수 비교', `${j(a, '와과')} ${b} 중 더 ${big ? '큰' : '작은'} 수는 무엇일까요?`, String(answer), [String(a === answer ? b : a)], dots('🔟', [{ label: String(a), icons: Math.floor(a / 10) }, { label: String(b), icons: Math.floor(b / 10) }]), Math.floor(a / 10) === Math.floor(b / 10) ? `십의 자리가 같으니 일의 자리를 비교하면 ${j(answer, '이가')} 더 ${big ? '커요' : '작아요'}.` : `십의 자리부터 비교하면 ${j(answer, '이가')} 더 ${big ? '커요' : '작아요'}.`, r); },
    (r) => { const start = ri(60, 95, r), seq = [start, start + 1, start + 2, start + 3, start + 4], hole = ri(1, 3, r), shown = seq.map((n, i) => i === hole ? '□' : n); return numberQ('pictograph', '빈칸 수', `${shown.join(', ')}에서 □에 알맞은 수는 무엇일까요?`, seq[hole], dots('●', [{ label: '1씩', icons: 1 }]), `1씩 커지는 수이므로 □는 ${seq[hole]}${ye(seq[hole])}.`); },
  ],
};

function nums2(list: number[]) { return list.map(String); }
