import { choiceQ, dec, dots, fracBar, fracText, gcd, numberQ, pick, ri, type GradeTable, j, ye } from './grade-helpers';

const geo = (shape: 'rectangle' | 'square' | 'right-triangle' | 'angle' | 'segment', label: string) => ({ kind: 'geometry' as const, shape, label });
const circ = (radius: number) => ({ kind: 'circle' as const, focus: 'given-radius' as const, radius, unit: 'cm' as const });
const band = (parts: { label: string; percent: number }[], mode: 'band' | 'pie', hidden: number[] = []) => ({ kind: 'ratio-graph' as const, mode, parts, hidden });
const dv = (tenths: number) => ({ kind: 'decimal' as const, tenths: Math.max(0, Math.min(9, tenths)) });
const SPORTS = ['축구', '피구', '줄넘기', '달리기'] as const;
const PRISM = ['', '', '', '삼각', '사각', '오각', '육각'] as const;

function percentParts(r: () => number): { label: string; percent: number }[] {
  for (let tries = 0; tries < 200; tries++) {
    const a = pick([10, 15, 20, 25, 30, 35, 40], r), b = pick([10, 15, 20, 25, 30, 35, 40], r), c = pick([10, 15, 20, 25, 30, 35, 40], r), d = 100 - a - b - c;
    if (d >= 10 && d <= 40 && new Set([a, b, c, d]).size === 4) return SPORTS.map((label, i) => ({ label, percent: [a, b, c, d][i] }));
  }
  return SPORTS.map((label, i) => ({ label, percent: [40, 30, 20, 10][i] }));
}

export const GRADE6: GradeTable = {
  plane: [
    (r) => { const d = ri(2, 9, r), q = ri(2, 6, r), n = ri(1, d - 1, r), answer = fracText(n, d * q); return choiceQ('plane', '분수÷자연수', `${n}/${d} ÷ ${q}의 값은 얼마일까요?`, answer, [fracText(n * q, d), fracText(n, d + q), fracText(q, n * d)], fracBar(n, d * q), `분수÷자연수는 분모에 자연수를 곱해 ${j(`${n}/${d * q}`, '이가')} 돼요${gcd(n, d * q) > 1 ? ` (기약분수: ${answer})` : ''}.`, r); },
    (r) => { const n = ri(1, 4, r), d = ri(n + 1, 6, r), k = ri(2, 8, r), a = n * k, answer = a * d / n; return numberQ('plane', '자연수÷분수', `${a} ÷ ${j(`${n}/${d}`, '은는')} 얼마일까요?`, answer, fracBar(n, d), `${a} ÷ ${n}/${d} = ${a} × ${d}/${n} = ${answer}${ye(answer)}.`, { hints: ['나눗셈을 곱셈으로 바꿀 때 나누는 분수는 분자와 분모를 바꿔요.', `${a} × ${j(`${d}/${n}`, '을를')} 계산해요.`, `${a} × ${d} ÷ ${n} = ${answer}${ye(answer)}.`] }); },
    (r) => { const b = ri(2, 6, r), d = ri(5, 9, r), k = ri(2, 6, r), a = b * k; return numberQ('plane', '분수÷분수', `${a}/${d} ÷ ${j(`${b}/${d}`, '은는')} 얼마일까요?`, k, fracBar(a, d), `분모가 같으면 분자끼리 나누어 ${a} ÷ ${b} = ${k}${ye(k)}.`); },
    (r) => { const kind = ri(0, 1, r); if (kind === 0) { const n = ri(1, 8, r), d = ri(n + 1, 9, r); return choiceQ('plane', '역수', `${n}/${d}의 역수는 얼마일까요?`, `${d}/${n}`, [`${n}/${d}`, `${d}/${d - n || 1}`, `${n + 1}/${d}`], fracBar(n, d), `분자와 분모를 서로 바꾼 ${j(`${d}/${n}`, '이가')} 역수예요.`, r); } const n = ri(2, 9, r); return choiceQ('plane', '역수', `${n}의 역수는 얼마일까요?`, `1/${n}`, [`${n}/1`, `1/${n + 1}`, `${n + 1}/${n}`], fracBar(1, n), `${n} = ${n}/1이므로 역수는 1/${n}${ye(`${1}/${n}`)}.`, r); },
    (r) => { const d = ri(2, 5, r) * 2, n = ri(3, 5, r), per = d * 2, answer = n * per / d; return numberQ('plane', '분수 나눗셈', `주스 ${n}/${d} L를 ${1}/${per} L씩 병에 나누어 담으면 몇 병이 될까요?`, answer, fracBar(n, d), `${n}/${d} ÷ 1/${per} = ${n}/${d} × ${per} = ${answer}병이에요.`); },
  ],
  lengthTime: [
    (r) => { const q = ri(2, 6, r), n = ri(2, 9, r) * q, whole = n / 10; return choiceQ('lengthTime', '소수÷자연수', `${dec(whole)} ÷ ${q}의 몫은 얼마일까요?`, dec(whole / q), [dec(whole / q * 10), dec(whole / q / 10), dec(whole / q + 1)], dv(Math.round(whole / q) % 10), `${dec(whole)} ÷ ${q} = ${dec(whole / q)}${ye(dec(whole / q))}.`, r); },
    (r) => { const d = pick([2, 4, 5, 8], r), a = ri(1, 9, r) * d / 2, answer = a * 10 / d; return numberQ('lengthTime', '자연수÷소수', `${a} ÷ ${j(`0.${d}`, '은는')} 얼마일까요?`, answer, dv(d), `${a} ÷ 0.${d} = ${a * 10} ÷ ${d} = ${answer}${ye(answer)}.`, { hints: ['나누는 수와 나누어지는 수에 똑같이 10을 곱해요.', `${a * 10} ÷ ${j(d, '을를')} 계산해요.`, `답은 ${answer}${ye(answer)}.`] }); },
    (r) => { const d = ri(2, 9, r), q = ri(2, 9, r), a = d * q; return numberQ('lengthTime', '소수÷소수', `${dec(a / 10)} ÷ ${j(dec(d / 10), '은는')} 얼마일까요?`, q, dv(d), `둘 다 10배 하면 ${a} ÷ ${d} = ${q}${ye(q)}.`); },
    (r) => { const q = ri(3, 8, r); let v = ri(15, 99, r) / 10; for (let t = 0; t < 30 && (Math.abs(v / q - Math.round(v / q)) < .12 || v / q < .7); t++) v = ri(15, 99, r) / 10; const est = Math.round(v / q), answer = String(est); return choiceQ('lengthTime', '몫 어림', `${dec(v)} ÷ ${q}의 몫은 약 얼마일까요? (가장 가까운 자연수로 어림해요)`, answer, [String(est + 1), String(est + 2), String(Math.max(0, est - 1))], dv(Math.round(v) % 10), `${dec(v)} ÷ ${q} = ${dec(v / q, 2)}이므로 약 ${answer}${ye(answer)}.`, r); },
    (r) => { const q = ri(3, 8, r), quo = ri(2, 9, r), rem = ri(1, q - 1, r) / 10 * (q > 10 ? 1 : 1), total = quo * q + rem; return choiceQ('lengthTime', '나머지 나타내기', `${dec(total, 1)} ÷ ${j(q, '을를')} 몫을 자연수까지만 구할 때 나머지는 얼마일까요?`, dec(rem, 1), [dec(rem * 10, 1), dec(rem / 10, 2), dec(quo, 1)], dv(Math.round(rem * 10)), `${q} × ${quo} = ${q * quo}이고 ${dec(total, 1)} − ${q * quo} = ${dec(rem, 1)}이므로 나머지는 ${dec(rem, 1)}${ye(dec(rem, 1))}.`, r); },
  ],
  fractionDecimal: [
    (r) => { const a = ri(2, 9, r), b = ri(2, 9, r); if (r() < .5) return choiceQ('fractionDecimal', '비', `남학생 ${a}명, 여학생 ${b}명이에요. 남학생 수와 여학생 수의 비를 바르게 쓴 것은 무엇일까요?`, `${a} : ${b}`, [`${b} : ${a}`, `${a} : ${a + b}`, `${a + b} : ${b}`], dots('🧒', [{ label: '남', icons: a }, { label: '여', icons: b }]), `남학생 수 : 여학생 수 = ${a} : ${b}${ye(b)}.`, r); return choiceQ('fractionDecimal', '비', `${a} : ${j(b, '을를')} 바르게 읽은 것은 무엇일까요?`, `${a} 대 ${b}`, [`${b} 대 ${a}`, `${a} 분의 ${b}`, `${a} 곱하기 ${b}`], dots('●', [{ label: '비', icons: 2 }]), `${a} : ${j(b, '은는')} “${a} 대 ${b}”라고 읽어요.`, r); },
    (r) => { const a = ri(1, 9, r), b = ri(a + 1, 10, r); return choiceQ('fractionDecimal', '비율', `비 ${a} : ${b}에서 기준량은 얼마일까요?`, String(b), [String(a), String(a + b), String(b - a || 1)], dots('●', [{ label: '기준량', icons: 3 }]), `비율 = 비교하는 양 ÷ 기준량이에요. ${a} : ${b}에서 기준량은 ${b}${ye(b)}.`, r); },
    (r) => { const total = pick([10, 20, 25, 50], r), part = ri(1, total - 1, r), answer = fracText(part, total); return choiceQ('fractionDecimal', '분수로 나타내기', `전체 ${total} 중 ${part}일 때, 전체에 대한 비율을 분수로 나타내면 무엇일까요?`, answer, [fracText(total, part), fracText(part + 1, total), fracText(part, total + 1)], fracBar(part, total > 12 ? 10 : total), `${j(`${part}/${total}`, '을를')} 약분하면 ${answer}${ye(answer)}.`, r); },
    (r) => { const d = pick([2, 4, 5, 10, 20, 25], r), n = ri(1, d - 1, r), value = n / d; return choiceQ('fractionDecimal', '소수로 나타내기', `비율 ${j(`${n}/${d}`, '을를')} 소수로 나타내면 무엇일까요?`, dec(value), [dec(value * 10), dec(value / 10), dec(1 - value)], dv(Math.round(value * 10) % 10), `${n} ÷ ${d} = ${dec(value)}${ye(dec(value))}.`, r); },
    (r) => { const kind = ri(0, 1, r); if (kind === 0) { const p = ri(1, 19, r) * 5; return numberQ('fractionDecimal', '백분율', `비율 ${j(dec(p / 100), '을를')} 백분율로 나타내면 몇 %일까요?`, p, dv(Math.round(p / 10) % 10), `${dec(p / 100)} × 100 = ${p}%예요.`); } const d = pick([2, 4, 5, 10, 20, 25], r), n = ri(1, d - 1, r), p = n * 100 / d; return numberQ('fractionDecimal', '백분율', `비율 ${j(`${n}/${d}`, '을를')} 백분율로 나타내면 몇 %일까요?`, p, fracBar(n, Math.min(d, 10)), `${n}/${d} × 100 = ${p}%예요.`); },
  ],
  circle: [
    (r) => { const d = ri(2, 12, r); return choiceQ('circle', '원주', `지름이 ${d} cm인 원의 원주는 지름의 약 몇 배일까요?`, '약 3.14배', ['약 2배', '약 6.28배', '약 1.57배'], circ(d / 2), '원주는 지름의 약 3.14배예요.', r); },
    (r) => choiceQ('circle', '원주율', '원의 둘레(원주)를 지름으로 나눈 값을 무엇이라고 할까요?', '원주율', ['반지름', '넓이', '대각선'], circ(3), '(원주) ÷ (지름) = (원주율)이에요. 원주율은 약 3.14예요.', r),
    (r) => { const rad = ri(2, 12, r), answer = dec(2 * 3.14 * rad, 2); return choiceQ('circle', '원의 둘레', `반지름이 ${rad} cm인 원의 둘레는 몇 cm일까요? (원주율 3.14)`, answer, [dec(3.14 * rad, 2), dec(3.14 * rad * rad, 2), dec(2 * rad, 2)], circ(rad), `2 × ${rad} × 3.14 = ${answer} cm예요.`, r); },
    (r) => { const rad = ri(2, 12, r), answer = dec(rad * rad * 3.14, 2); return choiceQ('circle', '원의 넓이', `반지름이 ${rad} cm인 원의 넓이는 몇 cm²일까요? (원주율 3.14)`, answer, [dec(2 * 3.14 * rad, 2), dec(rad * rad, 2), dec(rad * 3.14, 2)], circ(rad), `${rad} × ${rad} × 3.14 = ${answer} cm²예요.`, r); },
    (r) => { const rad = ri(2, 6, r), side = rad * 2, answer = dec(rad * rad * 3.14, 2); return choiceQ('circle', '원 활용', `한 변이 ${side} cm인 정사각형 안에 꼭 맞는 가장 큰 원을 그렸어요. 원의 넓이는 몇 cm²일까요? (원주율 3.14)`, answer, [dec(side * side, 2), dec(side * side * 3.14, 2), dec(side * 3.14, 2)], circ(rad), `원의 지름이 ${side} cm이므로 반지름은 ${rad} cm이고 넓이는 ${rad} × ${rad} × 3.14 = ${answer} cm²예요.`, r); },
  ],
  fraction: [
    (r) => { const a = ri(1, 5, r), b = ri(2, 6, r); return choiceQ('fraction', '비의 성질', `비 ${a} : ${j(b, '와과')} 비율이 같은 비는 무엇일까요?`, `${a * 2} : ${b * 2}`, [`${a + 2} : ${b + 2}`, `${b} : ${a}`, `${a} : ${b + 2}`], dots('●', [{ label: String(a), icons: a }, { label: String(b), icons: b }]), `두 항에 같은 수 2를 곱하면 ${a * 2} : ${b * 2}${ye(b * 2)}.`, r); },
    (r) => { const a = ri(1, 5, r), b = ri(2, 7, r), k = ri(2, 5, r); return numberQ('fraction', '비례식', `비례식 ${a} : ${b} = □ : ${b * k}에서 □에 알맞은 수는 무엇일까요?`, a * k, dots('●', [{ label: String(a), icons: a }, { label: String(b), icons: b }]), `${b}에 ${j(k, '을를')} 곱해 ${j(b * k, '이가')} 되었으므로 ${a}에도 ${j(k, '을를')} 곱해 ${a * k}${ye(a * k)}.`); },
    (r) => { const a = ri(2, 6, r), b = a === 6 ? 5 : ri(a + 1, 7, r), k = ri(2, 4, r), c = a * k; return numberQ('fraction', '비례식 계산', `비례식 ${a} : ${b} = ${c} : □에서 외항의 곱과 내항의 곱이 같음을 이용해 □를 구해 보세요.`, b * k, dots('⚖️', [{ label: '외항', icons: 2 }, { label: '내항', icons: 2 }]), `${a} × □ = ${b} × ${c}이므로 □ = ${b * c} ÷ ${a} = ${b * k}${ye(b * k)}.`); },
    (r) => { const a = ri(1, 4, r), b = ri(a + 1, 5, r), unit = ri(2, 6, r), total = (a + b) * unit, small = r() < .5, answer = small ? a * unit : b * unit; return numberQ('fraction', '비례배분', `사탕 ${total}개를 ${a} : ${j(b, '으로')} 나누어 가지려고 해요. ${small ? '적게' : '많이'} 가지는 쪽은 몇 개를 가질까요?`, answer, dots('🍬', [{ label: String(a), icons: Math.min(a, 6) }, { label: String(b), icons: Math.min(b, 6) }]), `전체를 ${j(a + b, '으로')} 나눈 ${unit}씩 ${small ? a : b}묶음이므로 ${answer}개예요.`); },
    (r) => { const n1 = ri(2, 5, r), price = ri(2, 9, r) * 100, n2 = ri(n1 + 1, 9, r); return numberQ('fraction', '생활 속 비례', `연필 ${n1}자루의 값이 ${n1 * price}원이에요. 같은 연필 ${n2}자루의 값은 얼마일까요?`, n2 * price, dots('✏️', [{ label: `${n1}자루`, icons: n1 }, { label: `${n2}자루`, icons: n2 }]), `연필 한 자루는 ${price}원이므로 ${price} × ${n2} = ${n2 * price}원이에요.`); },
  ],
  measurement: [
    (r) => { const n = ri(3, 6, r), prism = r() < .5; if (prism) return numberQ('measurement', '각기둥과 각뿔', `${PRISM[n]}기둥의 꼭짓점은 모두 몇 개일까요?`, n * 2, geo('rectangle', `${PRISM[n]}기둥`), `${PRISM[n]}기둥의 한 밑면에 꼭짓점이 ${n}개씩 있으므로 모두 ${n * 2}개예요.`); return numberQ('measurement', '각기둥과 각뿔', `${PRISM[n]}뿔의 면은 모두 몇 개일까요? (밑면과 옆면을 모두 세어요)`, n + 1, geo('right-triangle', `${PRISM[n]}뿔`), `밑면 1개와 옆면 ${n}개를 더해 ${n + 1}개예요.`); },
    (r) => { const w = ri(2, 4, r), h = ri(2, 3, r), layers = ri(2, 4, r); return numberQ('measurement', '쌓기나무', `쌓기나무를 가로 ${w}개, 세로 ${h}개로 깔고 ${layers}층으로 똑같이 쌓았어요. 쌓기나무는 모두 몇 개일까요?`, w * h * layers, { kind: 'array', rows: h, columns: w }, `한 층에 ${w} × ${h} = ${w * h}개이고 ${layers}층이므로 ${w * h * layers}개예요.`); },
    (r) => { const q = ri(0, 1, r); if (q === 0) return numberQ('measurement', '원기둥', '원기둥의 밑면은 모두 몇 개일까요?', 2, geo('rectangle', '원기둥'), '원기둥은 서로 평행하고 합동인 원 모양의 밑면이 2개예요.'); const rad = ri(2, 8, r), answer = dec(2 * 3.14 * rad, 2); return choiceQ('measurement', '원기둥', `원기둥의 전개도에서 밑면의 반지름이 ${rad} cm이면, 옆면(직사각형)의 가로는 밑면의 둘레와 같아요. 가로는 몇 cm일까요? (원주율 3.14)`, answer, [dec(3.14 * rad, 2), dec(3.14 * rad * rad, 2), dec(2 * rad, 2)], circ(rad), `2 × ${rad} × 3.14 = ${answer} cm예요.`, r); },
    (r) => { const q = ri(0, 2, r); if (q === 0) return numberQ('measurement', '원뿔과 구', '원뿔의 꼭짓점은 몇 개일까요?', 1, geo('right-triangle', '원뿔'), '원뿔은 뾰족한 꼭짓점이 1개예요.'); if (q === 1) return choiceQ('measurement', '원뿔과 구', '어느 방향에서 보아도 둥근 원 모양으로 보이는 입체도형은 무엇일까요?', '구', ['원기둥', '원뿔', '각기둥'], circ(4), '구는 어느 방향에서 보아도 원으로 보여요.', r); const rad = ri(2, 9, r); return numberQ('measurement', '원뿔과 구', `구의 반지름이 ${rad} cm이면 지름은 몇 cm일까요?`, rad * 2, circ(rad), `구의 지름은 반지름의 2배이므로 ${rad * 2} cm예요.`); },
    (r) => { const a = ri(2, 9, r), b = ri(2, 9, r), c = ri(2, 9, r); if (r() < .5) return numberQ('measurement', '겉넓이와 부피', `가로 ${a} cm, 세로 ${b} cm, 높이 ${c} cm인 직육면체의 부피는 몇 cm³일까요?`, a * b * c, geo('rectangle', `${a} × ${b} × ${c}`), `${a} × ${b} × ${c} = ${a * b * c} cm³예요.`); return numberQ('measurement', '겉넓이와 부피', `가로 ${a} cm, 세로 ${b} cm, 높이 ${c} cm인 직육면체의 겉넓이는 몇 cm²일까요?`, 2 * (a * b + b * c + c * a), geo('rectangle', `${a} × ${b} × ${c}`), `2 × (${a}×${b} + ${b}×${c} + ${c}×${a}) = ${2 * (a * b + b * c + c * a)} cm²예요.`, { hints: ['서로 다른 세 가지 면의 넓이를 구해요.', `${a}×${b}, ${b}×${c}, ${c}×${j(a, '을를')} 더한 뒤 2배 해요.`, `겉넓이는 ${2 * (a * b + b * c + c * a)} cm²예요.`] }); },
  ],
  pictograph: [
    (r) => { const parts = percentParts(r), i = ri(0, 3, r); return numberQ('pictograph', '띠그래프', `띠그래프에서 ${parts[i].label}의 비율은 몇 %일까요? (전체는 100%예요)`, parts[i].percent, band(parts, 'band', [i]), `${j(parts[i].label, '이가')} 차지하는 칸을 읽으면 ${parts[i].percent}%예요.`); },
    (r) => { const parts = percentParts(r), most = parts.reduce((m, p) => p.percent > m.percent ? p : m, parts[0]); return choiceQ('pictograph', '원그래프', '원그래프에서 가장 넓은 부분은 어느 항목일까요?', most.label, parts.filter(p => p !== most).map(p => p.label), band(parts, 'pie'), `${most.percent}%로 ${j(most.label, '이가')} 가장 넓어요.`, r); },
    (r) => { const total = pick([100, 200, 300, 400, 500], r), p = ri(1, 9, r) * 5; return numberQ('pictograph', '백분율 읽기', `조사한 학생이 모두 ${total}명이고 그중 ${p}%가 축구를 좋아해요. 축구를 좋아하는 학생은 몇 명일까요?`, total * p / 100, band([{ label: '축구', percent: p }, { label: '그 밖', percent: 100 - p }], 'band', [0]), `${total} × ${p}/100 = ${total * p / 100}명이에요.`); },
    (r) => { const parts = percentParts(r), a = ri(0, 3, r); let b = ri(0, 3, r); if (b === a) b = (a + 1) % 4; return numberQ('pictograph', '자료 비교', `띠그래프에서 ${j(parts[a].label, '와과')} ${parts[b].label}의 비율의 차는 몇 %일까요?`, Math.abs(parts[a].percent - parts[b].percent), band(parts, 'band'), `${Math.max(parts[a].percent, parts[b].percent)} − ${Math.min(parts[a].percent, parts[b].percent)} = ${Math.abs(parts[a].percent - parts[b].percent)}%예요.`); },
    (r) => { const parts = percentParts(r), a = ri(0, 3, r); let b = ri(0, 3, r); if (b === a) b = (a + 1) % 4; return numberQ('pictograph', '자료 해석', `띠그래프에서 ${j(parts[a].label, '와과')} ${parts[b].label}의 비율을 합하면 전체의 몇 %일까요?`, parts[a].percent + parts[b].percent, band(parts, 'band'), `${parts[a].percent} + ${parts[b].percent} = ${parts[a].percent + parts[b].percent}%예요.`); },
  ],
};

