import { choiceQ, dots, fracBar, numberQ, pick, ri, shuffle, type GradeTable, j, ye } from './grade-helpers';

const fmt = (n: number) => String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const dec = (n: number) => String(parseFloat(n.toFixed(2)));
const mixed = (n: number, d: number) => n >= d && n % d !== 0 ? `${Math.floor(n / d)} ${n % d}/${d}` : n % d === 0 ? String(n / d) : `${n}/${d}`;
const TIME_LABELS = ['1월', '2월', '3월', '4월', '5월', '6월'] as const;
const ANIMALS = ['토끼', '다람쥐', '고슴도치', '여우'] as const;
const decVisual = (tenths: number) => ({ kind: 'decimal' as const, tenths: Math.max(0, Math.min(9, tenths)) });
const bar = (labels: string[], values: number[], unit: string, hidden: number[] = [], line = false) => ({ kind: 'bar-graph' as const, labels, values, unit, line, hidden, step: 5 });
const tf = (op: 'slide' | 'flip-h' | 'flip-v' | 'rotate-cw90' | 'rotate-ccw90' | 'rotate-180', label?: string, mark?: 'top' | 'bottom' | 'left' | 'right') => ({ kind: 'transform' as const, op, label, mark });

const QUAD = [
  { name: '사다리꼴', clue: '평행한 변이 한 쌍이라도 있는 사각형' },
  { name: '평행사변형', clue: '마주 보는 두 쌍의 변이 서로 평행한 사각형' },
  { name: '마름모', clue: '네 변의 길이가 모두 같은 사각형' },
  { name: '직사각형', clue: '네 각이 모두 직각인 사각형' },
  { name: '정사각형', clue: '네 각이 모두 직각이고 네 변의 길이가 모두 같은 사각형' },
] as const;
const POLY = ['삼각형', '사각형', '오각형', '육각형', '칠각형', '팔각형'] as const;

export const GRADE4: GradeTable = {
  plane: [
    (r) => { const k = ri(2, 9, r), n = k * 10000; return choiceQ('plane', '만', `1만이 ${k}개이면 얼마일까요?`, fmt(n), [fmt(k * 1000), fmt(k * 100000), fmt(n + 1000)], dots('●', [{ label: '만', icons: k }]), `1만은 10000이므로 ${k}만은 ${fmt(n)}${ye(fmt(n))}.`, r); },
    (r) => { const k = ri(2, 9, r), n = k * 100000000; return choiceQ('plane', '억', `${k}억을 수로 쓰면 무엇일까요?`, fmt(n), [fmt(k * 10000000), fmt(k * 1000000000), fmt(k * 10000)], dots('●', [{ label: '억', icons: k }]), `1억은 100000000이므로 ${k}억은 ${fmt(n)}${ye(fmt(n))}.`, r); },
    (r) => choiceQ('plane', '조', '1조는 1억의 몇 배일까요?', '10000배', ['100배', '1000배', '100000배'], dots('●', [{ label: '조', icons: 1 }]), '1조는 1억이 10000개 모인 수예요.', r),
    (r) => { const digits = Array.from({ length: 8 }, () => ri(1, 9, r)), n = Number(digits.join('')), idx = ri(0, 6, r), pos = 7 - idx, value = digits[idx] * 10 ** pos; return choiceQ('plane', '자릿값', `${fmt(n)}에서 ${j(digits[idx], '이가')} 나타내는 값은 얼마일까요? (왼쪽에서 ${idx + 1}번째 숫자)`, fmt(value), [fmt(value * 10), fmt(value / 10 >= 1 ? value / 10 : digits[idx]), fmt(digits[idx])], dots('●', [{ label: fmt(n), icons: 4 }]), `이 숫자는 ${pos + 1}번째 자리에 있으므로 ${j(fmt(value), '을를')} 나타내요.`, r); },
    (r) => { const base = ri(100000000, 899999999, r); let other = base + (r() < .5 ? 1 : -1) * ri(1, 9, r) * 10 ** ri(3, 7, r); if (other < 100000000) other = base + 10 ** 7; const big = r() < .5, answer = big ? Math.max(base, other) : Math.min(base, other); return choiceQ('plane', '큰 수 비교', `${j(fmt(base), '와과')} ${fmt(other)} 중 더 ${big ? '큰' : '작은'} 수는 무엇일까요?`, fmt(answer), [fmt(base === answer ? other : base)], dots('●', [{ label: '높은 자리부터', icons: 3 }]), `높은 자리부터 차례로 비교하면 ${j(fmt(answer), '이가')} 더 ${big ? '커요' : '작아요'}.`, r); },
  ],
  lengthTime: [
    (r) => { const k = ri(1, 4, r); return numberQ('lengthTime', '각도', `직각 ${k}개를 이어 붙인 각의 크기는 몇 도일까요? (직각은 90°)`, 90 * k, { kind: 'geometry', shape: 'right-angle', label: `직각 ${k}개` }, `90 × ${k} = ${90 * k}°예요.`); },
    (r) => { const a = ri(0, 4, r) * 10, b = a + ri(3, 12, r) * 10; return numberQ('lengthTime', '각도 재기', `각도기로 각을 재었더니 한 변이 ${a}°, 다른 변이 ${b}°를 가리켜요. 각의 크기는 몇 도일까요?`, b - a, { kind: 'geometry', shape: 'angle', label: `${a}° ~ ${b}°` }, `${b} − ${a} = ${b - a}°예요.`); },
    (r) => { const x = ri(10, 170, r), answer = x < 90 ? '예각' : x === 90 ? '직각' : '둔각'; return choiceQ('lengthTime', '예각과 둔각', `크기가 ${x}°인 각은 예각, 직각, 둔각 중 무엇일까요?`, answer, ['예각', '직각', '둔각'], { kind: 'geometry', shape: 'angle', label: `${x}°` }, x < 90 ? `0°보다 크고 90°보다 작으면 예각이에요.` : x === 90 ? '90°는 직각이에요.' : '90°보다 크고 180°보다 작으면 둔각이에요.', r); },
    (r) => { const kind = pick(['예각삼각형', '직각삼각형', '둔각삼각형'] as const, r); let a: number, b: number, c: number; if (kind === '직각삼각형') { a = 90; b = ri(20, 70, r); c = 90 - b; } else if (kind === '둔각삼각형') { a = ri(100, 140, r); b = ri(15, 180 - a - 15, r); c = 180 - a - b; } else { a = ri(50, 70, r); b = ri(50, 70, r); c = 180 - a - b; if (c >= 90) { a = 60; b = 60; c = 60; } } return choiceQ('lengthTime', '삼각형 분류', `세 각이 ${a}°, ${b}°, ${c}°인 삼각형은 무엇일까요?`, kind, ['예각삼각형', '직각삼각형', '둔각삼각형'], { kind: 'geometry', shape: 'right-triangle', label: `${a}°, ${b}°, ${c}°` }, kind === '직각삼각형' ? '직각이 하나 있으므로 직각삼각형이에요.' : kind === '둔각삼각형' ? '둔각이 하나 있으므로 둔각삼각형이에요.' : '세 각이 모두 예각이므로 예각삼각형이에요.', r); },
    (r) => { if (r() < .6) { const a = ri(30, 90, r), b = ri(20, 80, r); return numberQ('lengthTime', '각도 계산', `삼각형의 두 각이 ${a}°, ${b}°예요. 나머지 한 각은 몇 도일까요?`, 180 - a - b, { kind: 'geometry', shape: 'right-triangle', label: `${a}°, ${b}°, ?` }, `삼각형의 세 각의 합은 180°이므로 180 − ${a} − ${b} = ${180 - a - b}°예요.`); } const a = ri(70, 120, r), b = ri(60, 110, r), c = ri(50, 100, r); return numberQ('lengthTime', '각도 계산', `사각형의 세 각이 ${a}°, ${b}°, ${c}°예요. 나머지 한 각은 몇 도일까요?`, 360 - a - b - c, { kind: 'geometry', shape: 'rectangle', label: `${a}°, ${b}°, ${c}°, ?` }, `사각형의 네 각의 합은 360°이므로 360 − ${a} − ${b} − ${c} = ${360 - a - b - c}°예요.`); },
  ],
  fractionDecimal: [
    (r) => { const from = ri(1, 4, r), by = ri(2, 6, r); return numberQ('fractionDecimal', '밀기', `도형의 왼쪽 끝이 모눈 왼쪽에서 ${from}칸 떨어져 있어요. 도형을 오른쪽으로 ${by}칸 밀면 왼쪽 끝은 몇 칸 떨어진 곳에 있을까요?`, from + by, tf('slide', `오른쪽으로 ${by}칸 밀기`), `밀기는 모양과 방향이 그대로이고 위치만 바뀌어요. ${from} + ${by} = ${from + by}칸이에요.`); },
    (r) => { const right = r() < .5, answer = right ? '오른쪽' : '아래쪽', from = right ? '왼쪽' : '위쪽'; return choiceQ('fractionDecimal', '뒤집기', `도형을 ${j(right ? '오른쪽' : '아래쪽', '으로')} 뒤집었어요. 원래 ${from}에 있던 ★은 뒤집은 도형에서 어느 쪽에 있을까요?`, answer, ['왼쪽', '오른쪽', '위쪽', '아래쪽'].filter(x => x !== answer && x !== from).concat(from), tf(right ? 'flip-h' : 'flip-v', `${j(right ? '오른쪽' : '아래쪽', '으로')} 뒤집기`, right ? 'left' : 'top'), `${j(right ? '오른쪽' : '아래쪽', '으로')} 뒤집으면 ${j(from, '와과')} ${j(answer, '이가')} 서로 바뀌어요.`, r); },
    (r) => { const cases = [{ op: 'rotate-cw90' as const, label: '시계 방향으로 90°', from: '위쪽', to: '오른쪽' }, { op: 'rotate-ccw90' as const, label: '시계 반대 방향으로 90°', from: '위쪽', to: '왼쪽' }, { op: 'rotate-180' as const, label: '180°', from: '위쪽', to: '아래쪽' }, { op: 'rotate-cw90' as const, label: '시계 방향으로 90°', from: '오른쪽', to: '아래쪽' }], c = pick(cases, r); return choiceQ('fractionDecimal', '돌리기', `도형을 ${c.label} 돌렸어요. 원래 ${c.from}에 있던 ★은 어느 쪽으로 옮겨 갈까요?`, c.to, ['위쪽', '아래쪽', '왼쪽', '오른쪽'].filter(x => x !== c.to), tf(c.op, `${c.label} 돌리기`, c.from === '위쪽' ? 'top' : 'right'), `${c.label} 돌리면 ${c.from}에 있던 ★이 ${j(c.to, '으로')} 가요.`, r); },
    (r) => { const mul = r() < .35, start = ri(1, 6, r), step = ri(2, 6, r); if (mul) { const s = ri(1, 3, r), seq = [s, s * 2, s * 4, s * 8]; return numberQ('fractionDecimal', '수 배열 규칙', `${seq.join(', ')}, □ 에서 □에 알맞은 수는 무엇일까요?`, s * 16, dots('●', [{ label: '2배씩', icons: 2 }]), `앞의 수의 2배가 되는 규칙이므로 ${seq[3]} × 2 = ${s * 16}${ye(s * 16)}.`); } const seq = [start, start + step, start + step * 2, start + step * 3]; return numberQ('fractionDecimal', '수 배열 규칙', `${seq.join(', ')}, □ 에서 □에 알맞은 수는 무엇일까요?`, start + step * 4, dots('●', [{ label: `${step}씩`, icons: step }]), `${step}씩 커지는 규칙이므로 ${seq[3]} + ${step} = ${start + step * 4}예요.`); },
    (r) => { if (r() < .5) { const a = ri(2, 9, r), b = ri(2, 9, r), c = ri(1, a + b - 1, r); return numberQ('fractionDecimal', '규칙을 식으로', `${a} + ${b} = ${c} + □ 에서 □에 알맞은 수는 무엇일까요? (등호 양쪽의 값은 같아요)`, a + b - c, dots('⚖️', [{ label: '왼쪽', icons: 3 }, { label: '오른쪽', icons: 3 }]), `${a} + ${b} = ${a + b}이므로 □ = ${a + b} − ${c} = ${a + b - c}예요.`); } const n = ri(4, 8, r); return numberQ('fractionDecimal', '규칙을 식으로', `바둑돌을 1개, 3개, 5개, 7개…처럼 2개씩 늘려 놓아요. ${n}번째에는 바둑돌을 모두 몇 개 놓을까요? (식: ${n} × 2 − 1)`, n * 2 - 1, dots('⚫', [{ label: '1번째', icons: 1 }, { label: '2번째', icons: 3 }, { label: '3번째', icons: 5 }]), `${n} × 2 − 1 = ${n * 2 - 1}개예요.`); },
  ],
  circle: [
    (r) => { const q = ri(0, 2, r); if (q === 0) return choiceQ('circle', '수직', '두 직선이 만나서 이루는 각이 직각일 때, 두 직선은 서로 어떤 관계일까요?', '수직', ['평행', '합동', '대칭'], { kind: 'geometry', shape: 'right-angle', label: '직각으로 만나요' }, '두 직선이 서로 직각으로 만나면 수직이에요.', r); if (q === 1) return choiceQ('circle', '수직', '삼각자의 직각 부분을 이용해 직선에 수직인 선을 그으려고 해요. 수직인 선과 처음 직선이 만나서 이루는 각은 몇 도일까요?', '90°', ['45°', '60°', '180°'], { kind: 'geometry', shape: 'right-angle', label: '수직선 긋기' }, '수직은 만나서 이루는 각이 직각(90°)이에요.', r); return choiceQ('circle', '수직', '직선 ㄱㄴ에 수직인 직선 ㄷㄹ이 있어요. 직선 ㄷㄹ을 ㄱㄴ에 대한 무엇이라고 할까요?', '수선', ['평행선', '대각선', '반직선'], { kind: 'geometry', shape: 'right-angle', label: 'ㄱㄴ ⟂ ㄷㄹ' }, '한 직선에 수직인 직선을 그 직선에 대한 수선이라고 해요.', r); },
    (r) => { const q = ri(0, 2, r); if (q === 0) return choiceQ('circle', '평행', '한 직선에 수직인 두 직선은 서로 어떤 관계일까요?', '평행', ['수직', '대각선', '대칭'], { kind: 'geometry', shape: 'line', label: '같은 직선에 수직인 두 직선' }, '한 직선에 수직인 두 직선은 서로 만나지 않으므로 평행해요.', r); if (q === 1) return choiceQ('circle', '평행', '평행한 두 직선 사이의 거리는 어디에서 재어도 어떨까요?', '항상 같아요', ['점점 길어져요', '점점 짧아져요', '재는 곳마다 달라요'], { kind: 'geometry', shape: 'line', label: '평행선' }, '평행한 두 직선 사이의 거리는 어디서나 같아요.', r); const d = ri(2, 9, r); return numberQ('circle', '평행', `평행한 두 직선 사이의 거리가 ${d} cm예요. 한쪽 끝에서 재었을 때와 다른 쪽 끝에서 재었을 때, 평행선 사이의 거리는 각각 몇 cm일까요? (한 곳을 답하세요)`, d, { kind: 'geometry', shape: 'line', label: `평행선 사이 ${d} cm` }, `평행선 사이의 거리는 어디서 재어도 ${d} cm예요.`); },
    (r) => { const q = pick(QUAD, r), others = QUAD.filter(x => x.name !== q.name).map(x => x.name); return choiceQ('circle', '사각형', `${j(q.clue, '은는')} 무엇일까요?`, q.name, others, { kind: 'geometry', shape: q.name === '정사각형' || q.name === '마름모' ? 'square' : 'rectangle', label: '사각형 탐구' }, `${j(q.clue, '을를')} ${q.name}이라고 해요.`, r, { hints: ['변의 평행과 길이, 각의 크기를 살펴봐요.', '정사각형은 직사각형이면서 마름모예요.', `정답은 ${q.name}${ye(q.name)}.`] }); },
    (r) => { const i = ri(2, 5, r), n = i + 3, name = POLY[i]; if (r() < .5) return choiceQ('circle', '다각형', `변이 ${n}개인 다각형의 이름은 무엇일까요?`, name, POLY.filter(x => x !== name).slice(0, 4), { kind: 'geometry', shape: 'rectangle', label: `변 ${n}개` }, `변이 ${n}개인 다각형은 ${name}${ye(name)}.`, r); return numberQ('circle', '다각형', `${name}의 꼭짓점은 모두 몇 개일까요?`, n, { kind: 'geometry', shape: 'rectangle', label: name }, `${j(name, '은는')} 변과 꼭짓점이 각각 ${n}개예요.`); },
    (r) => { const n = ri(4, 6, r), answer = n * (n - 3) / 2, name = POLY[n - 3]; return numberQ('circle', '대각선', `${name}에서 서로 이웃하지 않는 두 꼭짓점을 이은 선분(대각선)은 모두 몇 개일까요?`, answer, { kind: 'geometry', shape: 'rectangle', label: name }, `${name}의 대각선은 ${n} × ${n - 3} ÷ 2 = ${answer}개예요.`, { hints: ['한 꼭짓점에서 이웃한 두 점과 자기 자신을 뺀 점으로 선을 그어요.', `한 꼭짓점에서 ${n - 3}개씩 그을 수 있어요.`, `같은 선이 두 번 세어지므로 ${n} × ${n - 3} ÷ 2 = ${answer}개예요.`] }); },
  ],
  fraction: [
    (r) => { const d = ri(3, 9, r), proper = r() < .5, n = proper ? ri(1, d - 1, r) : ri(d, d * 2, r), answer = proper ? '진분수' : '가분수'; return choiceQ('fraction', '진분수', `${j(`${n}/${d}`, '은는')} 진분수일까요, 가분수일까요?`, answer, ['진분수', '가분수', '대분수'].filter(x => x !== answer && x !== '대분수').concat('대분수'), fracBar(n, d), proper ? '분자가 분모보다 작으므로 진분수예요.' : '분자가 분모와 같거나 크므로 가분수예요.', r); },
    (r) => { const d = ri(3, 9, r), w = ri(1, 4, r), rest = ri(1, d - 1, r), improper = w * d + rest, toMixed = r() < .5; if (toMixed) return choiceQ('fraction', '가분수와 대분수', `${j(`${improper}/${d}`, '을를')} 대분수로 나타내면 무엇일까요?`, `${w} ${rest}/${d}`, [`${w + 1} ${rest}/${d}`, `${w} ${rest + 1 > d ? rest : rest + 1}/${d}`, `${Math.max(1, w - 1)} ${rest}/${d}`], fracBar(improper, d), `${improper} ÷ ${d} = ${w} … ${rest}이므로 ${w} ${rest}/${d}${ye(d)}.`, r); return choiceQ('fraction', '가분수와 대분수', `${w} ${j(`${rest}/${d}`, '을를')} 가분수로 나타내면 무엇일까요?`, `${improper}/${d}`, [`${improper + 1}/${d}`, `${w + rest}/${d}`, `${improper}/${d + 1}`], fracBar(improper, d), `${w} × ${d} + ${rest} = ${improper}이므로 ${improper}/${d}${ye(d)}.`, r); },
    (r) => { const d = ri(3, 8, r), w1 = ri(1, 3, r), n1 = ri(1, d - 1, r); let w2 = ri(1, 3, r), n2 = ri(1, d - 1, r); if (w1 === w2 && n1 === n2) n2 = n1 === 1 ? 2 : n1 - 1; const a = w1 * d + n1, b = w2 * d + n2, answer = a > b ? `${w1} ${n1}/${d}` : `${w2} ${n2}/${d}`; return choiceQ('fraction', '크기 비교', `${w1} ${j(`${n1}/${d}`, '와과')} ${w2} ${n2}/${d} 중 더 큰 분수는 무엇일까요?`, answer, [a > b ? `${w2} ${n2}/${d}` : `${w1} ${n1}/${d}`], fracBar(Math.max(a, b), d), '자연수 부분을 먼저 비교하고, 같으면 분수 부분을 비교해요.', r); },
    (r, hard) => { const d = ri(4, 9, r); if (hard) { const w1 = ri(1, 3, r), n1 = ri(1, Math.floor(d / 2), r), w2 = ri(1, 3, r), n2 = ri(1, d - n1 - 1 || 1, r), total = (w1 + w2) * d + n1 + n2, answer = mixed(total, d); return choiceQ('fraction', '분수 덧셈', `${w1} ${n1}/${d} + ${w2} ${j(`${n2}/${d}`, '은는')} 얼마일까요?`, answer, [mixed(total + 1, d), mixed(total - 1, d), mixed(total + d, d)], fracBar(Math.min(total, d * 4), d), '자연수끼리, 분수끼리 더해요.', r); } const a = ri(1, d - 1, r), b = ri(1, d - a, r), answer = mixed(a + b, d); return choiceQ('fraction', '분수 덧셈', `${a}/${d} + ${j(`${b}/${d}`, '은는')} 얼마일까요?`, answer, [`${a + b}/${d * 2}`, mixed(a + b + 1, d), `${a * b}/${d}`], fracBar(a + b, d), `분모는 그대로 두고 분자끼리 더해 ${answer}${ye(answer)}.`, r); },
    (r, hard) => { const d = ri(4, 9, r); if (hard) { const w = ri(2, 4, r), n1 = ri(2, d - 1, r), n2 = ri(1, n1 - 1 || 1, r), w2 = ri(1, w - 1, r), total = (w - w2) * d + n1 - n2; return choiceQ('fraction', '분수 뺄셈', `${w} ${n1}/${d} − ${w2} ${j(`${n2}/${d}`, '은는')} 얼마일까요?`, mixed(total, d), [mixed(total + 1, d), mixed(total - 1, d), mixed(total + d, d)], fracBar(w * d + n1, d), '자연수끼리, 분수끼리 빼요.', r); } if (r() < .4) { const n = ri(1, d - 1, r), answer = `${d - n}/${d}`; return choiceQ('fraction', '분수 뺄셈', `1 − ${j(`${n}/${d}`, '은는')} 얼마일까요?`, answer, [`${n}/${d}`, `${d - n}/${d * 2}`, `${n + 1}/${d}`], fracBar(d, d), `1 = ${d}/${d}이므로 ${d}/${d} − ${n}/${d} = ${answer}${ye(answer)}.`, r); } const a = ri(2, d - 1, r), b = ri(1, a - 1, r), answer = `${a - b}/${d}`; return choiceQ('fraction', '분수 뺄셈', `${a}/${d} − ${j(`${b}/${d}`, '은는')} 얼마일까요?`, answer, [`${a - b}/${d * 2}`, `${a + b}/${d}`, `${Math.max(1, a - b + 1)}/${d}`], fracBar(a, d), `분모는 그대로 두고 분자끼리 빼서 ${answer}${ye(answer)}.`, r); },
  ],
  measurement: [
    (r) => { const o = ri(1, 9, r), t = ri(1, 9, r), h = ri(1, 9, r), n = `${o}.${t}${h}`, pos = ri(0, 2, r), shown = pos === 0 ? o : pos === 1 ? t : h, value = pos === 0 ? String(o) : pos === 1 ? `0.${t}` : `0.0${h}`; return choiceQ('measurement', '소수의 자릿값', `${n}에서 ${pos === 0 ? '일' : pos === 1 ? '소수 첫째' : '소수 둘째'} 자리 숫자 ${j(shown, '이가')} 나타내는 값은 얼마일까요?`, value, [`0.${shown}`, `0.0${shown}`, String(shown)].filter(x => x !== value).concat(`${shown}0`), decVisual(t), `${n}에서 ${j(shown, '은는')} ${j(value, '을를')} 나타내요.`, r); },
    (r) => { const a = ri(1, 9, r) / 10 + ri(0, 9, r) / 100, b = ri(1, 9, r) / 10; if (Math.abs(a - b) < .005) return choiceQ('measurement', '소수 크기 비교', '0.5와 0.45 중 더 큰 수는 무엇일까요?', '0.5', ['0.45'], decVisual(5), '0.5 = 0.50이므로 0.50이 0.45보다 커요.', r); const big = Math.max(a, b), small = Math.min(a, b); return choiceQ('measurement', '소수 크기 비교', `${j(dec(a), '와과')} ${dec(b)} 중 더 큰 수는 무엇일까요?`, dec(big), [dec(small)], decVisual(Math.round(big * 10)), '높은 자리부터 비교해요. 자릿수가 달라도 소수점을 맞추어 비교해요.', r); },
    (r) => { const a = ri(11, 49, r) / 10, b = ri(11, 49, r) / 100, sum = a + b; return choiceQ('measurement', '소수 덧셈', `${dec(a)} + ${j(dec(b), '은는')} 얼마일까요?`, dec(sum), [dec(sum + .1), dec(sum - .1), dec(sum + 1)], decVisual(Math.round(sum) % 10), '소수점의 자리를 맞추어 같은 자리끼리 더해요.', r); },
    (r) => { const a = ri(31, 99, r) / 10, b = ri(11, 29, r) / 100, diff = a - b; return choiceQ('measurement', '소수 뺄셈', `${dec(a)} − ${j(dec(b), '은는')} 얼마일까요?`, dec(diff), [dec(diff + .1), dec(diff - .1), dec(diff + 1)], decVisual(Math.round(diff) % 10), '소수점의 자리를 맞추어 같은 자리끼리 빼요.', r); },
    (r) => { const total = ri(25, 60, r) / 10, used = ri(5, 24, r) / 10, add = r() < .5; if (add) return choiceQ('measurement', '소수 생활 문제', `리본을 ${dec(total)} m 샀고 ${dec(used)} m를 더 샀어요. 모두 몇 m일까요?`, dec(total + used), [dec(total + used + .1), dec(total + used - .1), dec(total - used)], decVisual(Math.round(total + used) % 10), `${dec(total)} + ${dec(used)} = ${dec(total + used)} m예요.`, r); return choiceQ('measurement', '소수 생활 문제', `끈 ${dec(total)} m 중 ${dec(used)} m를 썼어요. 남은 끈은 몇 m일까요?`, dec(total - used), [dec(total - used + .1), dec(total - used - .1), dec(total + used)], decVisual(Math.round(total - used) % 10), `${dec(total)} − ${dec(used)} = ${dec(total - used)} m예요.`, r); },
  ],
  pictograph: [
    (r) => { const values = ANIMALS.map(() => ri(2, 9, r) * 5), i = ri(0, 3, r); return numberQ('pictograph', '막대그래프', `막대그래프에서 ${ANIMALS[i]}의 막대 높이는 눈금 ${values[i] / 5}칸이고, 눈금 한 칸은 5마리예요. ${j(ANIMALS[i], '은는')} 모두 몇 마리일까요?`, values[i], bar([...ANIMALS], values, '마리', [i]), `${values[i] / 5} × 5 = ${values[i]}마리예요.`); },
    (r) => { const values = TIME_LABELS.map(() => ri(2, 8, r) * 5), i = ri(0, 5, r); return numberQ('pictograph', '꺾은선그래프', `꺾은선그래프에서 ${TIME_LABELS[i]}의 점이 가리키는 값은 얼마일까요? (눈금을 읽어요)`, values[i], bar([...TIME_LABELS], values, '개', [i], true), `${TIME_LABELS[i]}의 점에서 옆으로 눈금을 읽으면 ${values[i]}예요.`); },
    (r) => { let values: number[] = [10, 15, 20, 35, 30, 25], diffs = [5, 5, 15, -5, -5], max = 15; for (let t = 0; t < 200; t++) { const next = [ri(2, 4, r) * 5]; for (let k = 1; k < 6; k++) next.push(Math.max(5, next[k - 1] + ri(-1, 3, r) * 5)); const d = next.slice(1).map((v, k) => v - next[k]), m = Math.max(...d); if (m > 0 && d.filter(x => x === m).length === 1) { values = next; diffs = d; max = m; break; } } const at = diffs.indexOf(max) + 1; return choiceQ('pictograph', '변화 읽기', '꺾은선그래프에서 앞의 달보다 가장 많이 늘어난 달은 언제일까요?', TIME_LABELS[at], TIME_LABELS.filter((_, k) => k !== at && k > 0).slice(0, 3), bar([...TIME_LABELS], values, '개', [], true), `${TIME_LABELS[at - 1]}에서 ${j(TIME_LABELS[at], '으로')} ${max}만큼 늘어 선이 가장 가파르게 올라갔어요.`, r); },
    (r) => { const values = ANIMALS.map(() => ri(2, 12, r) * 5), a = ri(0, 3, r); let b = ri(0, 3, r); if (b === a) b = (a + 1) % 4; if (values[a] === values[b]) values[b] += 5; return numberQ('pictograph', '자료 비교', `막대그래프에서 ${j(ANIMALS[a], '와과')} ${ANIMALS[b]}의 수는 몇 마리 차이가 날까요?`, Math.abs(values[a] - values[b]), bar([...ANIMALS], values, '마리'), `${Math.max(values[a], values[b])} − ${Math.min(values[a], values[b])} = ${Math.abs(values[a] - values[b])}마리 차이예요.`); },
    (r) => { const values = shuffle([ri(2, 4, r), ri(5, 7, r), ri(8, 10, r), ri(11, 13, r)].map(x => x * 5), r), most = values.indexOf(Math.max(...values)); return choiceQ('pictograph', '그래프 해석', '막대그래프에서 가장 많은 동물은 무엇일까요?', ANIMALS[most], ANIMALS.filter((_, k) => k !== most), bar([...ANIMALS], values, '마리'), `${values[most]}마리로 ${ANIMALS[most]}의 막대가 가장 높아요.`, r); },
  ],
};
