import { choiceQ, dec, dots, fmt, fracBar, fracText, j, lcm, numberQ, pick, ri, shuffle, type GradeTable, ye } from './grade-helpers';

const geo = (shape: 'rectangle' | 'square' | 'right-triangle' | 'angle' | 'segment', label: string) => ({ kind: 'geometry' as const, shape, label });
const dv = (tenths: number) => ({ kind: 'decimal' as const, tenths: Math.max(0, Math.min(9, tenths)) });
const circ = (radius: number) => ({ kind: 'circle' as const, focus: 'given-radius' as const, radius, unit: 'cm' as const });
const DEN_PAIRS = [[2, 3], [2, 5], [3, 4], [3, 5], [4, 5], [4, 6], [2, 7], [3, 8], [5, 6]] as const;

/** 5학년: 기본 주제 뒤에 이어 붙이는 주제들 (2022 개정 5~6학년군 성취기준 보완) */
export const GRADE5_EXTRA: Partial<GradeTable> = {
  plane: [
    // [6수01-05] 공배수
    (r) => { const [a, b] = pick([[2, 3], [3, 4], [4, 6], [3, 5], [2, 5], [4, 10], [6, 9], [5, 10]] as const, r), L = lcm(a, b), answer = L * ri(1, 3, r), onlyA = [1, 2, 3, 4, 5, 6, 7, 8].map(k => a * k).filter(x => x % b !== 0), onlyB = [1, 2, 3, 4, 5, 6, 7, 8].map(k => b * k).filter(x => x % a !== 0), wrongs = shuffle([...onlyA.slice(0, 2), ...onlyB.slice(0, 2)], r).slice(0, 3); return choiceQ('plane', '공배수', `${j(a, '와과')} ${b}의 공배수인 것은 어느 것일까요?`, String(answer), wrongs.map(String), dots('●', [{ label: String(a), icons: 3 }, { label: String(b), icons: 3 }]), `${a}씩, ${b}씩 뛰어 센 수 중 같은 수가 공배수예요. ${j(answer, '은는')} 두 수의 공배수예요.`, r); },
  ],
  lengthTime: [
    // [6수02-01] 대응 관계를 나타낸 표에서 규칙 찾기
    (r) => { const mul = r() < .5, k = ri(2, 6, r), c = ri(2, 7, r), x = ri(5, 9, r), f = (n: number) => mul ? n * k : n + c, answer = f(x); return numberQ('lengthTime', '대응 관계 표', `□가 1, 2, 3일 때 △는 ${f(1)}, ${f(2)}, ${f(3)}${ye(f(3))}. □가 ${x}일 때 △는 얼마일까요?`, answer, dots('▫', [{ label: '□ 1', icons: Math.min(f(1), 12) }, { label: '□ 2', icons: Math.min(f(2), 12) }, { label: '□ 3', icons: Math.min(f(3), 12) }]), mul ? `△는 □의 ${k}배예요. ${x} × ${k} = ${answer}${ye(answer)}.` : `△는 □보다 ${c} 커요. ${x} + ${c} = ${answer}${ye(answer)}.`, { hints: ['□가 1씩 커질 때 △가 어떻게 변하는지 살펴봐요.', mul ? `△가 ${k}씩 커져요. 1일 때 ${f(1)}이므로 □의 ${k}배예요.` : `1일 때 ${f(1)}이므로 □에 ${j(c, '을를')} 더한 값이에요.`, `${x}일 때 △는 ${answer}${ye(answer)}.`] }); },
    // [6수02-01] □, △를 사용한 식
    (r) => { const mul = r() < .5, k = ri(2, 6, r), c = ri(2, 7, r), f = (n: number) => mul ? n * k : n + c, answer = mul ? `□ × ${k} = △` : `□ + ${c} = △`; return choiceQ('lengthTime', '대응 관계 식', `□가 1, 2, 3일 때 △는 ${f(1)}, ${f(2)}, ${f(3)}${ye(f(3))}. □와 △의 관계를 식으로 바르게 나타낸 것은 무엇일까요?`, answer, mul ? [`□ + ${k} = △`, `△ × ${k} = □`, `□ × ${k + 1} = △`] : [`□ × ${c} = △`, `△ + ${c} = □`, `□ + ${c + 1} = △`], dots('▫', [{ label: '□ 1', icons: Math.min(f(1), 12) }, { label: '□ 2', icons: Math.min(f(2), 12) }]), mul ? `△는 □의 ${k}배이므로 □ × ${k} = △예요.` : `△는 □보다 ${c} 크므로 □ + ${c} = △예요.`, r); },
  ],
  fraction: [
    // [6수01-07] 분모가 다른 분수의 크기 비교
    (r) => { const [d1, d2] = pick(DEN_PAIRS, r); let n1 = ri(1, d1 - 1, r), n2 = ri(1, d2 - 1, r); if (n1 * d2 === n2 * d1) n2 = n2 === 1 ? 2 : n2 - 1; if (n1 * d2 === n2 * d1) n1 = n1 === 1 ? 2 : n1 - 1; const first = n1 * d2 > n2 * d1, answer = first ? `${n1}/${d1}` : `${n2}/${d2}`, other = first ? `${n2}/${d2}` : `${n1}/${d1}`, L = lcm(d1, d2); return choiceQ('fraction', '분수 크기 비교', `${j(`${n1}/${d1}`, '와과')} ${n2}/${d2} 중 더 큰 분수는 무엇일까요?`, answer, [other], fracBar(Math.max(n1 * (L / d1), n2 * (L / d2)), L), `통분하면 ${j(`${n1 * (L / d1)}/${L}`, '와과')} ${n2 * (L / d2)}/${L}이므로 ${j(answer, '이가')} 더 커요.`, r, { hints: ['분모가 다르면 먼저 통분해요.', `공통분모 ${j(L, '으로')} 통분해 분자를 비교해요.`, `통분한 분자 ${j(n1 * (L / d1), '와과')} ${j(n2 * (L / d2), '을를')} 비교하면 ${j(answer, '이가')} 더 커요.`] }); },
    // [6수01-08] 대분수가 포함된 분모가 다른 분수의 덧셈과 뺄셈
    (r) => { const [d1, d2] = pick(DEN_PAIRS, r), L = lcm(d1, d2), add = r() < .5, w2 = ri(1, 2, r), n2 = ri(1, d2 - 1, r), n1 = ri(1, d1 - 1, r), B = (w2 * d2 + n2) * (L / d2); let w1 = ri(1, 3, r); if (!add && (w1 * d1 + n1) * (L / d1) <= B) w1 = w2 + 2; const A = (w1 * d1 + n1) * (L / d1), top = add ? A + B : A - B, answer = fracText(top, L); return choiceQ('fraction', '대분수 덧셈·뺄셈', `${w1} ${n1}/${d1} ${add ? '+' : '−'} ${w2} ${n2}/${d2}의 값은 얼마일까요?`, answer, [fracText(top + 1, L), fracText(Math.max(1, top - 1), L), fracText(top + L, L)], fracBar(Math.min(top, L * 3), L), `통분해서 ${add ? '더하면' : '빼면'} ${answer}${ye(answer)}.`, r, { hints: ['분모를 통분해서 같게 만들어요.', '자연수는 자연수끼리, 분수는 분수끼리 계산해도 돼요.', `답은 ${answer}${ye(answer)}.`] }); },
    // [6수01-12] 분수와 소수의 크기 비교
    (r) => { const d = pick([2, 4, 5, 10], r), n = ri(1, d - 1, r), value = n / d; let x = Math.round((value + (r() < .5 ? 1 : -1) * ri(1, 3, r) / 10) * 100) / 100; if (x <= 0 || x >= 1 || Math.abs(x - value) < .005) x = Math.round((value >= .5 ? value - .15 : value + .15) * 100) / 100; const fracBigger = value > x, answer = fracBigger ? `${n}/${d}` : dec(x); return choiceQ('fraction', '분수와 소수 크기 비교', `${j(`${n}/${d}`, '와과')} ${dec(x)} 중 더 큰 수는 무엇일까요?`, answer, [fracBigger ? dec(x) : `${n}/${d}`], dv(Math.round(Math.max(value, x) * 10) % 10), `${n}/${d} = ${j(dec(value), '으로')} 바꾸어 비교하면 ${j(answer, '이가')} 더 커요.`, r, { hints: ['분수를 소수로, 또는 소수를 분수로 바꾸어 같은 꼴로 만들어요.', `${n}/${d} = ${n} ÷ ${d} = ${dec(value)}${ye(dec(value))}.`, `${j(dec(value), '와과')} ${j(dec(x), '을를')} 비교하면 ${j(answer, '이가')} 더 커요.`] }); },
    // [6수01-10] (자연수)÷(자연수)의 몫을 분수로
    (r) => { const b = ri(2, 9, r); let a = ri(1, 25, r); if (a % b === 0) a++; const answer = fracText(a, b); return choiceQ('fraction', '나눗셈의 몫을 분수로', `${a} ÷ ${b}의 몫을 분수로 나타내면 무엇일까요?`, answer, [fracText(b, a), fracText(a, b + 1), fracText(Math.max(1, a - 1), b)], fracBar(Math.min(a, b * 3), b), `나누는 수 ${j(b, '이가')} 분모, 나누어지는 수 ${j(a, '이가')} 분자이므로 ${a}/${b}${a > b ? ` = ${answer}` : ''}${ye(a > b ? String(answer) : `${a}/${b}`)}.`, r, { hints: ['(자연수)÷(자연수)의 몫은 분수로 나타낼 수 있어요.', '나누어지는 수가 분자, 나누는 수가 분모예요.', `${a} ÷ ${b} = ${a}/${b}${ye(`${a}/${b}`)}.`] }); },
  ],
  measurement: [
    // [6수03-12, 13] 직사각형과 정사각형의 넓이, 넓이 단위
    (r) => { const q = ri(0, 2, r); if (q === 0) { const w = ri(3, 15, r), h = ri(2, 12, r); return numberQ('measurement', '직사각형 넓이와 넓이 단위', `가로 ${w} cm, 세로 ${h} cm인 직사각형의 넓이는 몇 cm²일까요?`, w * h, geo('rectangle', `${w} cm × ${h} cm`), `직사각형의 넓이 = 가로 × 세로 = ${w} × ${h} = ${w * h} cm²예요.`); } if (q === 1) { const s = ri(2, 15, r); return numberQ('measurement', '직사각형 넓이와 넓이 단위', `한 변이 ${s} cm인 정사각형의 넓이는 몇 cm²일까요?`, s * s, geo('square', `한 변 ${s} cm`), `정사각형의 넓이 = 한 변 × 한 변 = ${s} × ${s} = ${s * s} cm²예요.`); } const m = ri(2, 9, r); return choiceQ('measurement', '직사각형 넓이와 넓이 단위', `1 m²는 10000 cm²예요. ${m} m²는 몇 cm²일까요?`, fmt(m * 10000), [fmt(m * 1000), fmt(m * 100000), fmt(m * 100)], geo('square', '1 m × 1 m'), `1 m = 100 cm이므로 1 m² = 100 × 100 = 10000 cm²예요. ${m} m² = ${fmt(m * 10000)} cm²예요.`, r); },
    // [6수03-14] 마름모의 넓이
    (r) => { const d1 = ri(2, 10, r) * 2, d2 = ri(2, 12, r); return numberQ('measurement', '마름모 넓이', `두 대각선의 길이가 ${d1} cm, ${d2} cm인 마름모의 넓이는 몇 cm²일까요?`, d1 * d2 / 2, geo('square', `대각선 ${d1} cm, ${d2} cm`), `마름모의 넓이 = 한 대각선 × 다른 대각선 ÷ 2 = ${d1} × ${d2} ÷ 2 = ${d1 * d2 / 2} cm²예요.`, { hints: ['마름모는 두 대각선을 이용해 넓이를 구해요.', '(한 대각선) × (다른 대각선)을 먼저 계산해요.', `${d1} × ${d2} ÷ 2 = ${d1 * d2 / 2} cm²예요.`] }); },
    // [6수03-03, 04] 직육면체의 겨냥도와 전개도
    (r) => { const q = ri(0, 3, r); if (q === 0) return numberQ('measurement', '겨냥도와 전개도', '직육면체의 겨냥도에서 보이는 모서리는 모두 몇 개일까요?', 9, geo('rectangle', '겨냥도'), '겨냥도에서 보이는 모서리는 실선 9개, 보이지 않는 모서리는 점선 3개예요.'); if (q === 1) return numberQ('measurement', '겨냥도와 전개도', '직육면체의 겨냥도에서 보이지 않는 모서리는 모두 몇 개일까요? (점선으로 그려요)', 3, geo('rectangle', '겨냥도'), '보이지 않는 모서리는 점선으로 나타내며 모두 3개예요.'); if (q === 2) return numberQ('measurement', '겨냥도와 전개도', '직육면체의 전개도에는 직사각형 모양의 면이 모두 몇 개 있을까요?', 6, geo('rectangle', '전개도'), '직육면체는 면이 6개이므로 전개도에도 면이 6개 있어요.'); const a = ri(2, 9, r), b = ri(2, 9, r), c = ri(2, 9, r); return numberQ('measurement', '겨냥도와 전개도', `전개도를 접어 가로 ${a} cm, 세로 ${b} cm, 높이 ${c} cm인 직육면체를 만들어요. 가로와 같은 길이의 모서리는 모두 몇 개일까요?`, 4, geo('rectangle', `${a} cm × ${b} cm × ${c} cm`), '직육면체에서 길이가 같은 모서리는 가로, 세로, 높이 방향으로 각각 4개씩 있어요.'); },
  ],
};

/** 6학년: 기본 주제 뒤에 이어 붙이는 주제들 */
export const GRADE6_EXTRA: Partial<GradeTable> = {
  plane: [
    // [6수01-11] 분모가 다른 분수÷분수
    (r) => { const [d1, d2] = pick([[2, 3], [3, 4], [4, 5], [2, 5], [5, 6], [3, 8]] as const, r), n1 = ri(1, d1 - 1, r), n2 = ri(1, d2 - 1, r), answer = fracText(n1 * d2, d1 * n2); return choiceQ('plane', '분모가 다른 분수÷분수', `${n1}/${d1} ÷ ${n2}/${d2}의 값은 얼마일까요?`, answer, [fracText(n1 * n2, d1 * d2), fracText(d1 * n2, n1 * d2), fracText(n1 * d2, d1 * n2 + 1)], fracBar(n1, d1), `나눗셈을 곱셈으로 바꾸고 나누는 분수의 분자와 분모를 바꾸어 ${n1}/${d1} × ${d2}/${n2} = ${answer}${ye(answer)}.`, r, { hints: ['분수의 나눗셈은 곱셈으로 바꾸어 계산해요.', '나누는 분수는 역수로 바꾸어 곱해요.', `${n1}/${d1} × ${d2}/${n2} = ${answer}${ye(answer)}.`] }); },
    // [6수01-11] 대분수의 나눗셈
    (r) => { const d = ri(2, 6, r), w = ri(1, 3, r), n = ri(1, d - 1, r), m = ri(2, 5, r), improper = w * d + n, answer = fracText(improper, d * m); return choiceQ('plane', '대분수÷자연수', `${w} ${n}/${d} ÷ ${m}의 값은 얼마일까요?`, answer, [fracText(improper * m, d), fracText(n, d * m), fracText(improper, d + m)], fracBar(Math.min(improper, d * 3), d), `대분수를 가분수로 바꾸면 ${improper}/${d}이고, ${improper}/${d} ÷ ${m} = ${improper}/${d * m}${answer === `${improper}/${d * m}` ? '' : ` = ${answer}`}${ye(answer === `${improper}/${d * m}` ? `${improper}/${d * m}` : String(answer))}.`, r, { hints: ['대분수를 가분수로 바꾸어요.', `${w} ${n}/${d} = ${improper}/${d}${ye(`${improper}/${d}`)}.`, `분모에 ${j(m, '을를')} 곱하면 ${improper}/${d * m} = ${answer}${ye(answer)}.`] }); },
  ],
  lengthTime: [
    // [6수01-14] (자연수)÷(자연수)의 몫을 소수로
    (r) => { const b = pick([2, 4, 5, 8], r); let a = ri(1, 30, r); if (a % b === 0) a++; const q = a / b, answer = dec(q); return choiceQ('lengthTime', '몫을 소수로 나타내기', `${a} ÷ ${b}의 몫을 소수로 나타내면 얼마일까요?`, answer, [dec(q * 10), dec(q / 10), dec(q + .1)], dv(Math.round(q * 10) % 10), `${a} ÷ ${b} = ${answer}${ye(answer)}. 나누어떨어지지 않으면 소수점 아래에 0을 내려 계속 나누어요.`, r, { hints: ['나누어떨어지지 않으면 몫에 소수점을 찍고 0을 내려 계속 나눠요.', `${a} ÷ ${j(b, '을를')} 소수점 아래까지 계산해요.`, `답은 ${answer}${ye(answer)}.`] }); },
  ],
  fractionDecimal: [
    // [6수01-12] 분수·소수·백분율로 나타낸 비율의 크기 비교
    (r) => { const f = pick([[1, 2], [3, 4], [2, 5], [3, 5], [1, 4], [4, 5], [1, 5], [7, 10]] as const, r), vf = f[0] / f[1]; let d = Math.round((vf + (ri(1, 4, r) * (r() < .5 ? 1 : -1)) / 20) * 100) / 100, p = Math.round((vf + (ri(1, 4, r) * (r() < .5 ? 1 : -1)) / 10) * 100); if (d <= 0 || d >= 1) d = Math.round((vf < .5 ? vf + .15 : vf - .15) * 100) / 100; if (p <= 0 || p >= 100) p = Math.round((vf < .5 ? vf + .3 : vf - .3) * 100); const items = [{ text: `${f[0]}/${f[1]}`, v: vf }, { text: dec(d), v: d }, { text: `${p}%`, v: p / 100 }]; const top = Math.max(...items.map(x => x.v)); if (items.filter(x => Math.abs(x.v - top) < .0001).length > 1) items[1] = { text: '0.01', v: .01 }; const best = items.reduce((m, x) => x.v > m.v ? x : m, items[0]); return choiceQ('fractionDecimal', '비율의 크기 비교', `비율 ${items[0].text}, ${items[1].text}, ${items[2].text} 중 가장 큰 것은 무엇일까요?`, best.text, items.filter(x => x !== best).map(x => x.text), dv(Math.round(top * 10) % 10), `모두 백분율로 바꾸어 비교하면 ${items.map(x => `${x.text} = ${Math.round(x.v * 100)}%`).join(', ')}이므로 ${j(best.text, '이가')} 가장 커요.`, r, { hints: ['분수, 소수, 백분율을 같은 꼴로 바꾸어 비교해요.', '모두 백분율(%)로 바꾸면 비교하기 쉬워요.', `가장 큰 것은 ${best.text}${ye(best.text)}.`] }); },
    // [6수02-03] 백분율의 활용
    (r) => { const price = ri(2, 20, r) * 500, p = pick([10, 20, 30, 40, 50], r), answer = price * p / 100; return numberQ('fractionDecimal', '백분율 활용', `정가가 ${price}원인 물건을 ${p}% 할인해서 팔아요. 할인 금액은 얼마일까요?`, answer, dv(p / 10), `${price} × ${p}/100 = ${answer}원이에요.`, { hints: ['할인율은 정가에 대한 비율이에요.', `${p}%는 ${p}/100${ye(`${p}/100`)}.`, `${price} × ${p}/100 = ${answer}원이에요.`] }); },
  ],
  measurement: [
    // [6수03-18] 부피 단위
    (r) => { const q = ri(0, 1, r); if (q === 0) { const m = ri(2, 9, r); return choiceQ('measurement', '부피 단위', `1 m³는 1000000 cm³예요. ${m} m³는 몇 cm³일까요?`, fmt(m * 1000000), [fmt(m * 100000), fmt(m * 10000000), fmt(m * 1000)], geo('square', '1 m × 1 m × 1 m'), `1 m = 100 cm이므로 1 m³ = 100 × 100 × 100 = 1000000 cm³예요.`, r); } const a = ri(2, 6, r), b = ri(2, 6, r), c = ri(2, 5, r); return numberQ('measurement', '부피 단위', `부피가 1 cm³인 쌓기나무를 가로 ${a}개, 세로 ${b}개, ${c}층으로 쌓았어요. 부피는 몇 cm³일까요?`, a * b * c, { kind: 'array', rows: b, columns: a }, `쌓기나무 ${a} × ${b} × ${c} = ${a * b * c}개이므로 부피는 ${a * b * c} cm³예요.`); },
    // [6수03-06, 08] 각기둥과 원기둥의 전개도
    (r) => { const q = ri(0, 2, r), n = ri(3, 6, r), names = ['', '', '', '삼각', '사각', '오각', '육각']; if (q === 0) return numberQ('measurement', '각기둥과 원기둥 전개도', `${names[n]}기둥의 전개도에는 면이 모두 몇 개 있을까요? (밑면과 옆면을 모두 세어요)`, n + 2, geo('rectangle', `${names[n]}기둥 전개도`), `밑면 2개와 옆면 ${n}개를 더해 ${n + 2}개예요.`); if (q === 1) return choiceQ('measurement', '각기둥과 원기둥 전개도', '원기둥의 전개도에서 옆면은 어떤 모양일까요?', '직사각형', ['원', '삼각형', '사다리꼴'], circ(3), '원기둥의 옆면을 펼치면 직사각형이 돼요.', r); const rad = ri(2, 8, r), h = ri(3, 12, r); return choiceQ('measurement', '각기둥과 원기둥 전개도', `밑면의 반지름이 ${rad} cm, 높이가 ${h} cm인 원기둥의 전개도에서 옆면의 세로는 몇 cm일까요?`, String(h), [String(rad), String(rad * 2), String(h + rad)], circ(rad), `옆면의 세로는 원기둥의 높이와 같으므로 ${h} cm예요.`, r); },
    // [6수03-09, 10] 쌓기나무를 위·앞·옆에서 본 모양
    (r) => { const w = ri(3, 4, r), d = ri(2, 3, r), heights = Array.from({ length: d }, () => Array.from({ length: w }, () => ri(1, 4, r))), q = ri(0, 2, r), visual = { kind: 'stack-grid' as const, heights }; if (q === 0) { const total = heights.flat().reduce((sum, n) => sum + n, 0); return numberQ('measurement', '쌓기나무 위·앞·옆', '위에서 본 자리마다 쌓기나무의 높이가 적혀 있어요. 쌓기나무는 모두 몇 개일까요?', total, visual, `자리별 높이를 모두 더하면 ${heights.flat().join(' + ')} = ${total}개예요.`); } const profile = q === 1 ? Array.from({ length: w }, (_, x) => Math.max(...heights.map(row => row[x]))) : heights.map(row => Math.max(...row)), direction = q === 1 ? '앞' : '옆', answer = profile.join('-'), lower = profile.map((n, i) => i === 0 ? Math.max(1, n - 1) : n).join('-'), higher = profile.map((n, i) => i === profile.length - 1 ? Math.min(5, n + 1) : n).join('-'), reversed = [...profile].reverse().join('-'); return choiceQ('measurement', '쌓기나무 위·앞·옆', `자리별 높이를 보고 ${direction}에서 본 각 줄의 가장 높은 층을 왼쪽부터 나타낸 것은 무엇일까요? (예: 3-2-4)`, answer, [lower, higher, reversed], visual, `${direction}에서 같은 줄에 겹친 기둥 중 가장 높은 층만 보이므로 ${answer}${ye(answer)}.`, r, { hints: [`${direction}에서 같은 줄에 놓인 높이를 묶어 봐요.`, '각 묶음에서 가장 큰 높이를 골라요.', `왼쪽부터 쓰면 ${answer}${ye(answer)}.`] }); },
    // [6수03-17, 19] 정육면체의 겉넓이와 부피
    (r) => { const a = ri(2, 12, r); if (r() < .5) return numberQ('measurement', '정육면체 겉넓이와 부피', `한 모서리가 ${a} cm인 정육면체의 겉넓이는 몇 cm²일까요?`, 6 * a * a, geo('square', `한 모서리 ${a} cm`), `정육면체의 면은 6개이고 한 면의 넓이가 ${a} × ${a}이므로 6 × ${a * a} = ${6 * a * a} cm²예요.`); return numberQ('measurement', '정육면체 겉넓이와 부피', `한 모서리가 ${a} cm인 정육면체의 부피는 몇 cm³일까요?`, a * a * a, geo('square', `한 모서리 ${a} cm`), `${a} × ${a} × ${a} = ${a * a * a} cm³예요.`); },
  ],
  pictograph: [
    // [6수04-05] 가능성을 수로 나타내기
    (r) => { const items = [['주사위를 던질 때 7의 눈이 나올 가능성', '0'], ['동전을 던질 때 그림 면이 나올 가능성', '1/2'], ['내일 해가 동쪽에서 뜰 가능성', '1'], ['주사위를 던질 때 짝수의 눈이 나올 가능성', '1/2'], ['주사위를 던질 때 3의 눈이 나올 가능성', '1/6'], ['빨간 공만 들어 있는 주머니에서 빨간 공을 꺼낼 가능성', '1'], ['1부터 5까지 적힌 카드에서 6이 적힌 카드를 뽑을 가능성', '0']] as const, [what, answer] = pick(items, r); return choiceQ('pictograph', '가능성을 수로', `${j(what, '을를')} 수로 나타내면 얼마일까요?`, answer, ['0', '1/2', '1', '1/6'].filter(x => x !== answer), dots('🎲', [{ label: '가능성', icons: 3 }]), `일이 일어날 가능성이 불가능하면 0, 반반이면 1/2, 확실하면 1로 나타내요.`, r); },
    // [6수04-06] 가능성에 근거한 판단
    (r) => { const red = ri(1, 7, r); let blue = ri(1, 7, r); if (red === blue) blue++; const total = red + blue, higherRed = red > blue, answer = fracText(red, total); return choiceQ('pictograph', '가능성 판단', `상자에 빨간 공 ${red}개와 파란 공 ${blue}개가 들어 있어요. 공 하나를 꺼낼 때 빨간 공이 나올 가능성을 분수로 나타내면 무엇일까요?`, answer, [fracText(blue, total), fracText(red, blue), fracText(red + 1, total)], dots('🔴', [{ label: '빨강', icons: red }, { label: '파랑', icons: blue }]), `전체 ${total}개 중 빨간 공이 ${red}개이므로 가능성은 ${red}/${total}${ye(`${red}/${total}`)}${higherRed ? '. 파란 공보다 빨간 공이 나올 가능성이 더 커요' : ''}.`, r); },
  ],
};
